# Generated by Django 5.2.13 on 2026-05-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coursegenerationjob',
            new_name='course_gene_tenant__aa6f07_idx',
            old_name='cgj_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='coursegenerationjob',
            new_name='course_gene_tenant__556c2f_idx',
            old_name='cgj_tenant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='coursegenerationjob',
            new_name='course_gene_created_b6aaff_idx',
            old_name='cgj_createdby_created_idx',
        ),
    ]
