// src/components/maic/InteractiveRenderer.tsx
//
// Renders interactive HTML modules (simulations, widgets, etc.) in a
// sandboxed iframe. Security: allow-scripts is enabled but
// allow-same-origin is explicitly omitted to prevent the sandboxed
// content from accessing the parent page's origin.
//
// MAIC-605: registers the iframe with useWidgetIframeStore on mount
// so the playback engine can dispatch teacher actions
// (widget_highlight, widget_setState, widget_annotation, widget_reveal)
// via postMessage. Unregisters on unmount or scene change. The
// optional `widgetConfig` prop carries the typed config the backend
// extracted from the embedded `<script id="widget-config">` block;
// it is reserved for the action engine (MAIC-606) — this component
// does not render it directly.

import React, { useState, useCallback, useEffect, useRef } from 'react';
import { Loader2, AlertTriangle } from 'lucide-react';
import { cn } from '../../lib/utils';
import { useWidgetIframeStore } from '../../lib/maic-v2/widget-iframe-store';
import type { WidgetConfig } from '../../types/widget';

interface InteractiveRendererProps {
  html: string;
  url?: string;
  sceneId: string;
  /** Optional typed widget config (backend already extracted +
   *  validated; we pass it through for MAIC-606's action engine).
   *  Omitted is fine — the iframe's internal JS still reads its own
   *  `<script id="widget-config">` block to bootstrap. */
  widgetConfig?: WidgetConfig;
  /** MAIC-607 uplink: optional callback invoked when the iframe
   *  posts a message back to the parent. The parent (typically the
   *  WS hook owner) forwards as `{action:'widget_event', ...}` so
   *  the backend's pendingWidgetEvents buffer (MAIC-603) sees the
   *  student's interaction. Filtered to messages whose source ===
   *  this iframe's contentWindow — never trusts random posters. */
  onWidgetEvent?: (event: string, payload: Record<string, unknown>) => void;
}

export const InteractiveRenderer = React.memo<InteractiveRendererProps>(
  function InteractiveRenderer({
    html,
    url,
    sceneId,
    widgetConfig: _widgetConfig,
    onWidgetEvent,
  }) {
    const [isLoading, setIsLoading] = useState(true);
    const [hasError, setHasError] = useState(false);
    const iframeRef = useRef<HTMLIFrameElement | null>(null);

    const handleLoad = useCallback(() => {
      setIsLoading(false);
    }, []);

    const handleError = useCallback(() => {
      setIsLoading(false);
      setHasError(true);
    }, []);

    // MAIC-605: register/unregister iframe with the widget-iframe
    // store keyed by sceneId. The callback closes over iframeRef so
    // a late dispatch (after unmount) can detect and noop instead
    // of throwing on a dead contentWindow.
    useEffect(() => {
      const sendMessage = (type: string, payload: Record<string, unknown>) => {
        const win = iframeRef.current?.contentWindow;
        if (!win) return;
        // Sandboxed iframe with allow-scripts but NO allow-same-origin
        // means contentWindow.origin is "null" — `targetOrigin: '*'`
        // is the only legal value. The widget HTML is generated by us,
        // so this is the same trust boundary as the iframe's own JS.
        win.postMessage({ type, ...payload }, '*');
      };

      const store = useWidgetIframeStore.getState();
      store.registerIframe(sceneId, sendMessage);
      store.setActiveScene(sceneId);

      return () => {
        const cleanupStore = useWidgetIframeStore.getState();
        cleanupStore.registerIframe(sceneId, null);
        // Only clear active scene if it's still us — avoids racing
        // with a sibling scene that already took over.
        if (cleanupStore.activeSceneId === sceneId) {
          cleanupStore.setActiveScene(null);
        }
      };
    }, [sceneId]);

    // MAIC-607: parent listens for postMessage from this iframe and
    // forwards via onWidgetEvent. Filtered by event.source so only
    // messages from THIS iframe's contentWindow are accepted —
    // critical security boundary in a sandboxed-iframe setting where
    // any other window could try to drive the WS uplink.
    useEffect(() => {
      if (!onWidgetEvent) return;

      const handler = (e: MessageEvent) => {
        const win = iframeRef.current?.contentWindow;
        if (!win || e.source !== win) return;
        const data = e.data;
        if (typeof data !== 'object' || data === null) return;
        const eventName = (data as { type?: unknown }).type;
        if (typeof eventName !== 'string' || !eventName) return;
        // Strip `type` from the payload so the backend gets a clean
        // `event + payload` shape (mirrors the wire format defined
        // in MAIC-603's WidgetEvent TypedDict).
        const { type: _t, ...payload } = data as Record<string, unknown>;
        onWidgetEvent(eventName, payload);
      };

      window.addEventListener('message', handler);
      return () => window.removeEventListener('message', handler);
    }, [onWidgetEvent]);

    if (hasError) {
      return (
        <div className="flex flex-col items-center justify-center h-full bg-gray-50 text-gray-500 gap-3">
          <AlertTriangle className="h-8 w-8 text-amber-400" />
          <p className="text-sm font-medium">Failed to load interactive content</p>
          <p className="text-xs text-gray-400">
            The interactive module could not be rendered. Please try reloading.
          </p>
        </div>
      );
    }

    // If a URL is provided and no inline HTML, use the URL directly
    const useUrl = url && !html;

    return (
      <div className="relative w-full h-full rounded-lg border border-gray-200 overflow-hidden bg-white">
        {/* Loading overlay */}
        {isLoading && (
          <div className="absolute inset-0 flex items-center justify-center bg-white/80 z-10">
            <div className="flex flex-col items-center gap-2">
              <Loader2 className="h-6 w-6 text-primary-500 animate-spin" />
              <p className="text-xs text-gray-400">Loading interactive content...</p>
            </div>
          </div>
        )}

        {/* Sandboxed iframe */}
        <iframe
          ref={iframeRef}
          key={sceneId}
          className={cn(
            'w-full h-full border-0',
            isLoading && 'invisible',
          )}
          sandbox="allow-scripts"
          title="Interactive content"
          onLoad={handleLoad}
          onError={handleError}
          {...(useUrl
            ? { src: url }
            : { srcDoc: html }
          )}
        />
      </div>
    );
  },
);
