# Generated by Django 5.2.13 on 2026-05-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0033_rename_compliance__tenant__cat_idx_compliance__tenant__4dc237_idx_and_more'),
        ('translations', '0002_review_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contenttranslation',
            name='trn_unique_per_src_field_lang',
        ),
        migrations.AlterUniqueTogether(
            name='contenttranslation',
            unique_together={('tenant', 'source_type', 'source_id', 'field', 'target_language')},
        ),
    ]
