"""Action protocol — Pydantic models + JSON schema for the 21 action types.

Direct port of upstream OpenMAIC/lib/types/action.ts. See actions.py
header for the category breakdown and the 1000×562 whiteboard frame
contract.
"""
from .actions import (
    ALL_ACTION_TYPES,
    Action,
    ActionTypeLiteral,
    DiscussionAction,
    FIRE_AND_FORGET_ACTIONS,
    LaserAction,
    PlayVideoAction,
    SLIDE_ONLY_ACTIONS,
    SYNC_ACTIONS,
    SpeechAction,
    SpotlightAction,
    WbClearAction,
    WbCloseAction,
    WbDeleteAction,
    WbDrawChartAction,
    WbDrawCodeAction,
    WbDrawLatexAction,
    WbDrawLineAction,
    WbDrawShapeAction,
    WbDrawTableAction,
    WbDrawTextAction,
    WbEditCodeAction,
    WbOpenAction,
    WidgetAnnotationAction,
    WidgetHighlightAction,
    WidgetRevealAction,
    WidgetSetStateAction,
    export_json_schema,
    filter_for_scene,
    validate_action,
    validate_actions,
)

__all__ = [
    "Action",
    "ActionTypeLiteral",
    "ALL_ACTION_TYPES",
    "FIRE_AND_FORGET_ACTIONS",
    "SLIDE_ONLY_ACTIONS",
    "SYNC_ACTIONS",
    "SpotlightAction",
    "LaserAction",
    "SpeechAction",
    "WbOpenAction",
    "WbCloseAction",
    "WbClearAction",
    "WbDeleteAction",
    "WbDrawTextAction",
    "WbDrawShapeAction",
    "WbDrawChartAction",
    "WbDrawLatexAction",
    "WbDrawTableAction",
    "WbDrawLineAction",
    "WbDrawCodeAction",
    "WbEditCodeAction",
    "PlayVideoAction",
    "DiscussionAction",
    "WidgetHighlightAction",
    "WidgetSetStateAction",
    "WidgetAnnotationAction",
    "WidgetRevealAction",
    "validate_action",
    "validate_actions",
    "filter_for_scene",
    "export_json_schema",
]
