# Generated by Django 5.0.1 on 2026-02-21

from django.db import migrations, models
import django.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("reminders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="remindercampaign",
            name="automation_key",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="remindercampaign",
            name="source",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("AUTOMATED", "Automated")],
                default="MANUAL",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="remindercampaign",
            index=models.Index(fields=["tenant", "source", "created_at"], name="reminder_cam_tenant__efcc47_idx"),
        ),
        migrations.AddIndex(
            model_name="remindercampaign",
            index=models.Index(fields=["tenant", "reminder_type", "source"], name="reminder_cam_tenant__2a45ba_idx"),
        ),
        migrations.AddIndex(
            model_name="remindercampaign",
            index=models.Index(fields=["automation_key"], name="reminder_cam_automat_38f8e2_idx"),
        ),
        migrations.AddConstraint(
            model_name="remindercampaign",
            constraint=models.UniqueConstraint(
                condition=django.db.models.Q(source="AUTOMATED") & ~django.db.models.Q(automation_key=""),
                fields=("tenant", "automation_key"),
                name="uniq_auto_reminder_campaign_per_tenant_key",
            ),
        ),
    ]
