# Generated by Django 5.2.11 on 2026-02-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_remindercampaign_source_and_automation_key'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='remindercampaign',
            new_name='reminder_ca_tenant__851f01_idx',
            old_name='reminder_cam_tenant__efcc47_idx',
        ),
        migrations.RenameIndex(
            model_name='remindercampaign',
            new_name='reminder_ca_tenant__0d6e88_idx',
            old_name='reminder_cam_tenant__2a45ba_idx',
        ),
        migrations.RenameIndex(
            model_name='remindercampaign',
            new_name='reminder_ca_automat_1e590f_idx',
            old_name='reminder_cam_automat_38f8e2_idx',
        ),
    ]
