# Generated by Django 5.2.11 on 2026-03-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_add_remindercampaign_tenant_manager_and_delivery_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reminderdelivery',
            new_name='rem_del_camp_status_idx',
            old_name='reminder_del_campaign_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reminderdelivery',
            new_name='rem_del_tch_status_idx',
            old_name='reminder_del_teacher_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reminderdelivery',
            new_name='rem_del_stat_created_idx',
            old_name='reminder_del_status_created_idx',
        ),
    ]
