# Generated by Django 5.2.13 on 2026-05-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maic_pbl', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='maicpblsession',
            new_name='maic_pbl_se_tenant__76074e_idx',
            old_name='maic_pbl_se_tenant__a3c4f1_idx',
        ),
        migrations.RenameIndex(
            model_name='maicpblsession',
            new_name='maic_pbl_se_tenant__580fe4_idx',
            old_name='maic_pbl_se_tenant__7d2e09_idx',
        ),
    ]
