# Generated by Django 5.2.11 on 2026-02-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_is_actionable'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_teacher_d92bc4_idx',
            old_name='notificatio_teacher_action_idx',
        ),
    ]
