# Generated by Django 5.2.11 on 2026-03-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_is_archived'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notif_tnt_tch_created_idx',
            old_name='notif_tenant_teacher_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notif_tnt_tch_act_read_idx',
            old_name='notif_tenant_teacher_action_read_idx',
        ),
    ]
