# Generated by Django 5.2.13 on 2026-05-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_rename_notif_tenant_teacher_created_idx_notif_tnt_tch_created_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REMINDER', 'Reminder'), ('COURSE_ASSIGNED', 'Course Assigned'), ('ASSIGNMENT_DUE', 'Assignment Due'), ('ANNOUNCEMENT', 'Announcement'), ('SYSTEM', 'System'), ('DISCUSSION_REPLY', 'Discussion Reply')], default='SYSTEM', max_length=20),
        ),
    ]
