# Generated by Django 5.0.1 on 2026-02-02 03:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("courses", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super Admin"),
                            ("SCHOOL_ADMIN", "School Admin"),
                            ("TEACHER", "Teacher"),
                            ("HOD", "Head of Department"),
                            ("IB_COORDINATOR", "IB Coordinator"),
                        ],
                        default="TEACHER",
                        max_length=20,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True, help_text="School employee ID", max_length=50
                    ),
                ),
                (
                    "subjects",
                    models.JSONField(
                        blank=True, default=list, help_text="List of subjects taught"
                    ),
                ),
                (
                    "grades",
                    models.JSONField(
                        blank=True, default=list, help_text="List of grades taught"
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("date_of_joining", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "teacher_groups",
                    models.ManyToManyField(
                        blank=True, related_name="members", to="courses.teachergroup"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(fields=["email"], name="users_email_4b85f2_idx"),
                    models.Index(
                        fields=["tenant", "role"], name="users_tenant__b30c7b_idx"
                    ),
                    models.Index(
                        fields=["tenant", "is_active"], name="users_tenant__2f74ee_idx"
                    ),
                ],
            },
        ),
    ]
