# Generated by Django 5.0.1 on 2026-02-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_notification_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, default="", help_text="Short profile description"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="designation",
            field=models.CharField(
                blank=True,
                help_text="e.g. PGT, TGT, PRT, HOD, Vice Principal",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True,
                help_text="e.g. Science, Mathematics, Languages",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="employee_id",
            field=models.CharField(
                blank=True, help_text="School-assigned Teacher ID", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="grades",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of grades/classes e.g. ['Class 9', 'Class 10']",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="subjects",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of subjects taught e.g. ['Mathematics', 'Physics']",
            ),
        ),
    ]
