# Generated by Django 5.0.1 on 2026-02-16 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_must_change_password"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="user",
            new_name="users_is_dele_21b557_idx",
            old_name="users_is_dele_abc123_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_tenant__4c454d_idx",
            old_name="users_tenant__def456_idx",
        ),
    ]
