# Generated by Django 5.2.11 on 2026-02-26 02:37

import apps.users.models
import django.db.models.deletion
import utils.storage_paths
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_demobooking'),
        ('users', '0006_rename_users_is_dele_abc123_idx_users_is_dele_21b557_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=utils.storage_paths.profile_picture_upload_to),
        ),
        migrations.CreateModel(
            name='TeacherInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('token', models.CharField(default=apps.users.models._generate_invitation_token, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_invitations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'teacher_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='teacher_inv_token_2d905e_idx'), models.Index(fields=['tenant', 'status'], name='teacher_inv_tenant__75ffab_idx'), models.Index(fields=['email'], name='teacher_inv_email_cf8201_idx')],
            },
        ),
    ]
