# Generated by Django 5.2.11 on 2026-04-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_profile_picture_teacherinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrollment_date',
            field=models.DateField(blank=True, help_text='Student enrollment date', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='grade_level',
            field=models.CharField(blank=True, default='', help_text='e.g. Grade 9, Year 11', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_email',
            field=models.EmailField(blank=True, default='', help_text='Parent/guardian contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, default='', help_text='e.g. Section A, Room 201', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, default='', help_text='School-assigned Student ID', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SCHOOL_ADMIN', 'School Admin'), ('TEACHER', 'Teacher'), ('HOD', 'Head of Department'), ('IB_COORDINATOR', 'IB Coordinator'), ('STUDENT', 'Student')], default='TEACHER', max_length=20),
        ),
    ]
