# Generated by Django 5.2.11 on 2026-04-12 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial_academic_structure'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0020_add_grade_section_fks'),
        ('tenants', '0013_initial_academic_structure'),
        ('users', '0008_user_enrollment_date_user_grade_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade_fk',
            field=models.ForeignKey(blank=True, help_text="Student's current grade (FK to academic Grade model)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.grade'),
        ),
        migrations.AddField(
            model_name='user',
            name='section_fk',
            field=models.ForeignKey(blank=True, help_text="Student's current section (FK to academic Section model)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.section'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'grade_fk'], name='users_tenant__2a4754_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'section_fk'], name='users_tenant__fed70f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['student_id'], name='users_student_2d3a08_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employee_id'], name='users_employe_55e465_idx'),
        ),
    ]
