# Generated by Django 5.2.13 on 2026-05-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_rename_attendance_tenant__1a9b2c_idx_attendance_tenant__e63c6a_idx_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0051_alter_aichatbotknowledge_managers_and_more'),
        ('tenants', '0033_rename_compliance__tenant__cat_idx_compliance__tenant__4dc237_idx_and_more'),
        ('users', '0016_teacherinvitation_invitation_role'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordhistory',
            new_name='password_hi_user_id_53e9ab_idx',
            old_name='password_hi_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='samlauthevent',
            new_name='saml_auth_e_tenant__5c1f35_idx',
            old_name='saml_auth_e_tenant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='samlauthevent',
            new_name='saml_auth_e_decisio_8fa922_idx',
            old_name='saml_auth_e_decision_created_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'role', 'is_active'], name='users_tenant__38df1a_idx'),
        ),
    ]
