# Generated by Django 5.2.11 on 2026-02-21 09:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_tenant_maintenance_mode_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsCollectorCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_name', models.CharField(max_length=64, unique=True)),
                ('watermark_ts', models.DateTimeField(blank=True, null=True)),
                ('watermark_id', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ops_collector_cursors',
            },
        ),
        migrations.CreateModel(
            name='OpsDeadLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=255)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ops_dead_letters',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('week_of_month', models.PositiveSmallIntegerField(default=1)),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='SUNDAY', max_length=16)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=180)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_schedules', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_maintenance_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ops_maintenance_schedules',
            },
        ),
        migrations.CreateModel(
            name='OpsActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('reason', models.TextField(blank=True, default='')),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ops_action_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_runs', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='ops.maintenanceschedule')),
            ],
            options={
                'db_table': 'ops_maintenance_runs',
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['status', 'starts_at'], name='ops_mainten_status_89516c_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('synthetic', 'Synthetic'), ('internal', 'Internal'), ('harness', 'Harness')], max_length=20)),
                ('category', models.CharField(choices=[('availability_probe', 'Availability Probe'), ('auth_probe', 'Auth Probe'), ('background_jobs', 'Background Jobs'), ('deliverability', 'Deliverability'), ('webhook_delivery', 'Webhook Delivery'), ('harness_external', 'Harness External'), ('maintenance', 'Maintenance')], max_length=32)),
                ('severity', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('INFO', 'Info')], default='P2', max_length=10)),
                ('status', models.CharField(choices=[('FAIL', 'Fail'), ('RECOVER', 'Recover'), ('INFO', 'Info')], max_length=10)),
                ('event_ts', models.DateTimeField(db_index=True)),
                ('ingest_ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_key', models.CharField(max_length=255, unique=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=10)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ops_events', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ops_events',
                'ordering': ['-event_ts'],
                'indexes': [models.Index(fields=['tenant', 'event_ts'], name='ops_events_tenant__177005_idx'), models.Index(fields=['category', 'event_ts'], name='ops_events_categor_1c25b1_idx'), models.Index(fields=['status', 'event_ts'], name='ops_events_status_93a805_idx'), models.Index(fields=['source', 'event_ts'], name='ops_events_source_fc43b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpsHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down'), ('MAINTENANCE', 'Maintenance')], default='HEALTHY', max_length=20)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('theme_consecutive_failures', models.PositiveIntegerField(default=0)),
                ('auth_consecutive_failures', models.PositiveIntegerField(default=0)),
                ('theme_probe_ok', models.BooleanField(default=True)),
                ('auth_probe_ok', models.BooleanField(default=True)),
                ('last_probe_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('last_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('freshness_seconds', models.PositiveIntegerField(default=0)),
                ('last_probe_error', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ops_health_snapshot', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ops_health_snapshots',
                'indexes': [models.Index(fields=['current_status'], name='ops_health__current_b352b0_idx'), models.Index(fields=['last_probe_at'], name='ops_health__last_pr_4f124d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpsIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=5)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('TENANT', 'Tenant')], max_length=10)),
                ('rule_id', models.CharField(db_index=True, max_length=64)),
                ('dedupe_key', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKED', 'Acknowledged'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=10)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mttr_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_ops_incidents', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ops_incidents', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ops_incidents',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='ops_inciden_status_c66655_idx'), models.Index(fields=['tenant', 'status'], name='ops_inciden_tenant__cc8a72_idx'), models.Index(fields=['rule_id', 'status'], name='ops_inciden_rule_id_069e03_idx')],
            },
        ),
    ]
