# Generated by Django 5.2.11 on 2026-02-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_opsrouteerror_opsreplayrun_opsreplaystep_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='opsactionapproval',
            new_name='ops_action__approva_92393f_idx',
            old_name='ops_action__approva_758d79_idx',
        ),
        migrations.RenameIndex(
            model_name='opsreplayrun',
            new_name='ops_replay__tenant__cce886_idx',
            old_name='ops_replay__tenant__24f5f9_idx',
        ),
        migrations.RenameIndex(
            model_name='opsreplayrun',
            new_name='ops_replay__status_156b5d_idx',
            old_name='ops_replay__status_795cd6_idx',
        ),
        migrations.RenameIndex(
            model_name='opsreplaystep',
            new_name='ops_replay__run_id_7072bb_idx',
            old_name='ops_replay__run_id_4f894f_idx',
        ),
        migrations.RenameIndex(
            model_name='opsreplaystep',
            new_name='ops_replay__case_id_7090d1_idx',
            old_name='ops_replay__case_id_caed20_idx',
        ),
        migrations.RenameIndex(
            model_name='opsrouteerror',
            new_name='ops_route_e_tenant__6398f4_idx',
            old_name='ops_route__tenant__416fbe_idx',
        ),
        migrations.RenameIndex(
            model_name='opsrouteerror',
            new_name='ops_route_e_portal_5f6486_idx',
            old_name='ops_route__portal_15c9b0_idx',
        ),
        migrations.RenameIndex(
            model_name='opsrouteerror',
            new_name='ops_route_e_is_lock_6a60a8_idx',
            old_name='ops_route__is_lock_7164de_idx',
        ),
    ]
