# Generated by Django 5.2.13 on 2026-05-13 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_rename_ops_action__approva_758d79_idx_ops_action__approva_92393f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='start_time',
            field=models.TimeField(default=datetime.time(1, 0)),
        ),
    ]
