# Generated by Django 5.0.1 on 2026-02-02 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("progress", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teacherprogress",
            name="content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="courses.content",
            ),
        ),
        migrations.AddField(
            model_name="teacherprogress",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="teacherprogress",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignmentsubmission",
            unique_together={("assignment", "teacher")},
        ),
        migrations.AddIndex(
            model_name="teacherprogress",
            index=models.Index(
                fields=["teacher", "course"], name="teacher_pro_teacher_d34bd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherprogress",
            index=models.Index(
                fields=["teacher", "status"], name="teacher_pro_teacher_898779_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherprogress",
            index=models.Index(
                fields=["course", "status"], name="teacher_pro_course__2629c9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teacherprogress",
            unique_together={("teacher", "course", "content")},
        ),
    ]
