# Generated by GPT-5.2 on 2026-02-04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
        ("progress", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="courses.content",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="generation_source",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("VIDEO_AUTO", "Auto-generated from video")],
                default="MANUAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="generation_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="progress.assignment",
                    ),
                ),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("is_auto_generated", models.BooleanField(default=False)),
                ("generation_model", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "quizzes"},
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="progress.quiz",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question_type",
                    models.CharField(
                        choices=[("MCQ", "Multiple Choice"), ("SHORT_ANSWER", "Short Answer")],
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField()),
                ("options", models.JSONField(blank=True, default=list)),
                ("correct_answer", models.JSONField(blank=True, default=dict)),
                ("explanation", models.TextField(blank=True, default="")),
                ("points", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "quiz_questions",
                "ordering": ["quiz", "order"],
            },
        ),
        migrations.CreateModel(
            name="QuizSubmission",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="progress.quiz",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("answers", models.JSONField(blank=True, default=dict)),
                ("score", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "quiz_submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="quizquestion",
            index=models.Index(fields=["quiz", "order"], name="quiz_q_quiz_or_idx"),
        ),
        migrations.AddIndex(
            model_name="quizsubmission",
            index=models.Index(fields=["teacher", "submitted_at"], name="quiz_s_teacher__idx"),
        ),
        migrations.AlterUniqueTogether(
            name="quizsubmission",
            unique_together={("quiz", "teacher")},
        ),
    ]

