# Generated by Django 5.0.1 on 2026-02-15 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_assignment_soft_delete_fields"),
        ("progress", "0003_quizzes_and_assignment_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="quizquestion",
            new_name="quiz_questi_quiz_id_76bc24_idx",
            old_name="quiz_q_quiz_or_idx",
        ),
        migrations.RenameIndex(
            model_name="quizsubmission",
            new_name="quiz_submis_teacher_9323d4_idx",
            old_name="quiz_s_teacher__idx",
        ),
        migrations.AddField(
            model_name="assignment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["course", "is_active"], name="assignments_course__eb2ee8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["due_date", "is_active"], name="assignments_due_dat_c68cce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignmentsubmission",
            index=models.Index(
                fields=["assignment", "status"], name="assignment__assignm_68808b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignmentsubmission",
            index=models.Index(fields=["teacher", "status"], name="assignment__teacher_0372b4_idx"),
        ),
        migrations.AddIndex(
            model_name="assignmentsubmission",
            index=models.Index(fields=["submitted_at"], name="assignment__submitt_040795_idx"),
        ),
        migrations.AddIndex(
            model_name="teacherprogress",
            index=models.Index(
                fields=["teacher", "status", "completed_at"], name="teacher_pro_teacher_23af77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherprogress",
            index=models.Index(fields=["last_accessed"], name="teacher_pro_last_ac_dac411_idx"),
        ),
    ]
