# Generated by Django 5.0.1 on 2026-02-09 02:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_content_media_asset"),
        ("progress", "0004_assignment_soft_delete_fields"),
        ("tenants", "0003_tenant_plans_features"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseSkipRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "certificate_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to uploaded certificate file",
                        max_length=1024,
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Teacher's reason for skipping"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes on review decision"
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "course_skip_requests",
                "ordering": ["-created_at"],
            },
        ),
        # RenameIndex operations removed - already done in 0004_assignment_soft_delete_fields
        migrations.AddField(
            model_name="courseskiprequest",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skip_requests",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="courseskiprequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_skip_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="courseskiprequest",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skip_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="courseskiprequest",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skip_requests",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="courseskiprequest",
            index=models.Index(
                fields=["tenant", "status"], name="course_skip_tenant__913b69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseskiprequest",
            index=models.Index(
                fields=["teacher", "status"], name="course_skip_teacher_76d0f9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseskiprequest",
            unique_together={("teacher", "course")},
        ),
    ]
