# Generated by Codex on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("progress", "0005_courseskiprequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("MCQ", "Multiple Choice"),
                    ("SHORT_ANSWER", "Short Answer"),
                    ("TRUE_FALSE", "True/False"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="selection_mode",
            field=models.CharField(
                choices=[("SINGLE", "Single Select"), ("MULTIPLE", "Multiple Select")],
                default="SINGLE",
                max_length=20,
            ),
        ),
    ]
