# Generated by Django 5.2.11 on 2026-02-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_teacherquestclaim'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseskiprequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='courseskiprequest',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseskiprequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='courseskiprequest',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='courseskiprequest',
            name='tenant',
        ),
        migrations.RenameIndex(
            model_name='teacherquestclaim',
            new_name='teacher_que_teacher_ab6699_idx',
            old_name='teacher_que_teacher_ad9057_idx',
        ),
        migrations.RenameIndex(
            model_name='teacherquestclaim',
            new_name='teacher_que_teacher_01435d_idx',
            old_name='teacher_que_teacher_e0a053_idx',
        ),
        migrations.DeleteModel(
            name='CourseSkipRequest',
        ),
    ]
