# Generated by Django 5.2.11 on 2026-03-26 21:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_rename_chat_messa_session_m3n4o5_idx_chat_messag_session_597c4e_idx_and_more'),
        ('progress', '0010_skills_and_certifications'),
        ('tenants', '0010_tenant_stripe_customer_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='star', help_text='Icon identifier for the frontend', max_length=50)),
                ('color', models.CharField(default='#6C63FF', help_text='Hex color', max_length=7)),
                ('category', models.CharField(choices=[('milestone', 'Milestone'), ('streak', 'Streak'), ('completion', 'Completion'), ('skill', 'Skill'), ('special', 'Special')], max_length=50)),
                ('criteria_type', models.CharField(choices=[('xp_threshold', 'XP Threshold'), ('courses_completed', 'Courses Completed'), ('streak_days', 'Streak Days'), ('content_completed', 'Content Completed'), ('manual', 'Manual')], max_length=50)),
                ('criteria_value', models.PositiveIntegerField(default=0, help_text='Threshold value for auto-award')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'badge_definitions',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GamificationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xp_per_content_completion', models.PositiveIntegerField(default=10)),
                ('xp_per_course_completion', models.PositiveIntegerField(default=50)),
                ('xp_per_assignment_submission', models.PositiveIntegerField(default=15)),
                ('xp_per_quiz_submission', models.PositiveIntegerField(default=15)),
                ('xp_per_streak_day', models.PositiveIntegerField(default=2)),
                ('streak_freeze_max', models.PositiveIntegerField(default=2, help_text='Max streak freezes per month')),
                ('leaderboard_enabled', models.BooleanField(default=True)),
                ('leaderboard_anonymize', models.BooleanField(default=False, help_text='Show initials instead of names')),
                ('opt_out_allowed', models.BooleanField(default=True, help_text='Allow teachers to opt out of gamification')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gamification_config',
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=10)),
                ('rank', models.PositiveIntegerField()),
                ('xp_total', models.PositiveIntegerField(default=0)),
                ('xp_period', models.PositiveIntegerField(default=0, help_text='XP earned in this period')),
                ('snapshot_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'leaderboard_snapshots',
                'ordering': ['-snapshot_date', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='TeacherBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_reason', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'teacher_badges',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('freeze_count_this_month', models.PositiveIntegerField(default=0)),
                ('freeze_used_today', models.BooleanField(default=False)),
                ('streak_frozen_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher_streaks',
            },
        ),
        migrations.CreateModel(
            name='TeacherXPSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('level_name', models.CharField(default='Associate Educator', max_length=100)),
                ('xp_this_month', models.PositiveIntegerField(default=0)),
                ('xp_this_week', models.PositiveIntegerField(default=0)),
                ('last_xp_at', models.DateTimeField(blank=True, null=True)),
                ('opted_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher_xp_summaries',
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xp_amount', models.IntegerField()),
                ('reason', models.CharField(choices=[('content_completion', 'Content Completion'), ('course_completion', 'Course Completion'), ('assignment_submission', 'Assignment Submission'), ('quiz_submission', 'Quiz Submission'), ('streak_bonus', 'Streak Bonus'), ('badge_award', 'Badge Award'), ('admin_adjust', 'Admin Adjustment'), ('quest_reward', 'Quest Reward')], max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('reference_id', models.UUIDField(blank=True, help_text='ID of related object (content, course, etc.)', null=True)),
                ('reference_type', models.CharField(blank=True, default='', help_text='Type of related object', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'xp_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='certificationtype',
            name='unique_certtype_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='courseskill',
            name='unique_course_skill',
        ),
        migrations.RemoveConstraint(
            model_name='skill',
            name='unique_skill_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='teacherskill',
            name='unique_teacher_skill',
        ),
        migrations.RenameIndex(
            model_name='assignment',
            new_name='assignments_tenant__805365_idx',
            old_name='assignments_tenant__ca_idx',
        ),
        migrations.RenameIndex(
            model_name='assignment',
            new_name='assignments_tenant__95fb13_idx',
            old_name='assignments_tenant__da_idx',
        ),
        migrations.RenameIndex(
            model_name='assignmentsubmission',
            new_name='assignment__tenant__1696e1_idx',
            old_name='assgn_sub_tenant__as_idx',
        ),
        migrations.RenameIndex(
            model_name='assignmentsubmission',
            new_name='assignment__tenant__788380_idx',
            old_name='assgn_sub_tenant__ts_idx',
        ),
        migrations.RenameIndex(
            model_name='certificationtype',
            new_name='certificati_tenant__99313d_idx',
            old_name='certtype_tenant_name_idx',
        ),
        migrations.RenameIndex(
            model_name='courseskill',
            new_name='course_skil_course__fd8577_idx',
            old_name='courseskill_course_skill_idx',
        ),
        migrations.RenameIndex(
            model_name='courseskill',
            new_name='course_skil_skill_i_4f26c2_idx',
            old_name='courseskill_skill_level_idx',
        ),
        migrations.RenameIndex(
            model_name='quizquestion',
            new_name='quiz_questi_tenant__c36383_idx',
            old_name='quiz_questi_tenant__q_idx',
        ),
        migrations.RenameIndex(
            model_name='quizsubmission',
            new_name='quiz_submis_tenant__57a7d3_idx',
            old_name='quiz_submis_tenant__ts_idx',
        ),
        migrations.RenameIndex(
            model_name='skill',
            new_name='skills_tenant__164f80_idx',
            old_name='skill_tenant_category_idx',
        ),
        migrations.RenameIndex(
            model_name='skill',
            new_name='skills_tenant__3d2216_idx',
            old_name='skill_tenant_name_idx',
        ),
        migrations.RenameIndex(
            model_name='teachercertification',
            new_name='teacher_cer_tenant__69fb85_idx',
            old_name='tcert_tenant_teacher_status_idx',
        ),
        migrations.RenameIndex(
            model_name='teachercertification',
            new_name='teacher_cer_tenant__492616_idx',
            old_name='tcert_tenant_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='teachercertification',
            new_name='teacher_cer_expires_418a53_idx',
            old_name='tcert_expires_status_idx',
        ),
        migrations.RenameIndex(
            model_name='teachercertification',
            new_name='teacher_cer_tenant__7c8519_idx',
            old_name='tcert_tenant_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='teacherprogress',
            new_name='teacher_pro_tenant__18c898_idx',
            old_name='teacher_pro_tenant__tc_idx',
        ),
        migrations.RenameIndex(
            model_name='teacherprogress',
            new_name='teacher_pro_tenant__c0287e_idx',
            old_name='teacher_pro_tenant__ts_idx',
        ),
        migrations.RenameIndex(
            model_name='teacherprogress',
            new_name='teacher_pro_tenant__71192a_idx',
            old_name='teacher_pro_tenant__cs_idx',
        ),
        migrations.RenameIndex(
            model_name='teacherquestclaim',
            new_name='teacher_que_tenant__14556d_idx',
            old_name='teacher_que_tenant__tcd_idx',
        ),
        migrations.RenameIndex(
            model_name='teacherquestclaim',
            new_name='teacher_que_tenant__902da8_idx',
            old_name='teacher_que_tenant__tqk_idx',
        ),
        migrations.RenameIndex(
            model_name='teacherskill',
            new_name='teacher_ski_tenant__8008d2_idx',
            old_name='teacherskill_tenant_teacher_idx',
        ),
        migrations.RenameIndex(
            model_name='teacherskill',
            new_name='teacher_ski_tenant__633518_idx',
            old_name='teacherskill_tenant_skill_idx',
        ),
        migrations.RenameIndex(
            model_name='teacherskill',
            new_name='teacher_ski_teacher_9bdcbd_idx',
            old_name='teacherskill_teacher_level_idx',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='certificationtype',
            name='validity_months',
            field=models.IntegerField(default=12, help_text='Number of months the certification is valid', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='teacherprogress',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_progress', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='teacherquestclaim',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_quest_claims', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='certificationtype',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='courseskill',
            unique_together={('course', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherskill',
            unique_together={('teacher', 'skill')},
        ),
        migrations.AddField(
            model_name='badgedefinition',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_definitions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='gamificationconfig',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_config', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='leaderboardsnapshot',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaderboardsnapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_snapshots', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='teacherbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='progress.badgedefinition'),
        ),
        migrations.AddField(
            model_name='teacherbadge',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherbadge',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_badges', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='teacherstreak',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherstreak',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_streaks', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='teacherxpsummary',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp_summary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherxpsummary',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_xp_summaries', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='xptransaction',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xptransaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='badgedefinition',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='leaderboardsnapshot',
            index=models.Index(fields=['tenant', 'period', 'snapshot_date', 'rank'], name='leaderboard_tenant__fccbd3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboardsnapshot',
            unique_together={('tenant', 'teacher', 'period', 'snapshot_date')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherbadge',
            unique_together={('teacher', 'badge')},
        ),
        migrations.AddIndex(
            model_name='teacherstreak',
            index=models.Index(fields=['tenant', 'current_streak'], name='teacher_str_tenant__81f33e_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherxpsummary',
            index=models.Index(fields=['tenant', 'total_xp'], name='teacher_xp__tenant__5c48be_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherxpsummary',
            index=models.Index(fields=['tenant', 'level'], name='teacher_xp__tenant__ea5cce_idx'),
        ),
        migrations.AddIndex(
            model_name='xptransaction',
            index=models.Index(fields=['tenant', 'teacher'], name='xp_transact_tenant__87bf92_idx'),
        ),
        migrations.AddIndex(
            model_name='xptransaction',
            index=models.Index(fields=['tenant', 'teacher', 'reason'], name='xp_transact_tenant__f856f4_idx'),
        ),
        migrations.AddIndex(
            model_name='xptransaction',
            index=models.Index(fields=['created_at'], name='xp_transact_created_709fcf_idx'),
        ),
    ]
