"""Grok (xAI) image generation adapter — MAIC-905.

Source: THU-MAIC/OpenMAIC lib/media/adapters/grok-image-adapter.ts
        (read for API contract; re-implemented in Python per ADR-001a).
        Mirrors the golden pattern at apps/maic/media/adapters/openai_image.py
        (MAIC-903) — same class shape, same error matrix, same SSRF guard,
        same upload_media re-host. Only the bits the Grok API contract
        forces us to change are different.

Used by:
  - apps/maic/media/orchestrator.py — calls .generate() after resolving
    this adapter from the registry
  - apps/maic/media/views.py — POST /api/maic/v2/media/generate-image/
    when tenant_config.image_provider == "grok"

Grok's Images API is OpenAI-compatible:
  - Endpoint: POST {base_url}/images/generations
  - Auth: Bearer token
  - Request body: {model, prompt, n, response_format} — NO size/quality
    (xAI ignores them; model itself selects standard vs pro quality)
  - Response: {data: [{url, revised_prompt, b64_json?}, ...]}

Key deltas vs the OpenAI golden pattern:
  - Default base URL is https://api.x.ai/v1 (not api.openai.com)
  - Default model is "grok-imagine-image" (per upstream docstring)
  - Request body OMITS ``size`` and ``quality`` — Grok rejects them;
    model id is what selects standard ($0.02) vs pro ($0.07)
  - Cost table maps model id → flat per-image price (no size buckets)

Discipline (identical to MAIC-903):
  - aiohttp imported lazily inside generate() so tests can inject a
    fake via monkeypatch.setitem(sys.modules, "aiohttp", fake)
  - SSRF guard on tenant-supplied base_url; skipped for the default
    xAI URL (well-known public endpoint, no need to DNS-resolve twice)
  - Error matrix:
      401/403 → MaicConfigError (auth — permanent, no retry)
      429    → MaicProviderError (rate limited — retry)
      4xx    → MaicProviderError (other 4xx; could be transient)
      5xx    → MaicProviderError (server fault — retry)
      ClientError → MaicProviderError (network — retry)
      Parse failure → MaicProviderError (server returned bad shape)
  - Snippets truncated to 200 chars before going into error messages
  - upload_media re-hosts the generated bytes so the URL outlives
    Grok's CDN TTL
"""
from __future__ import annotations

import logging
from typing import ClassVar

from apps.maic.exceptions import MaicConfigError, MaicProviderError
from apps.maic.media.providers import MediaProviderAdapter, register_adapter
from apps.maic.media.storage import upload_media
from apps.maic.media.types import ImageGenerationRequest, ImageGenerationResult
from apps.integrations_chat.ssrf_guard import SSRFError, validate_webhook_host


logger = logging.getLogger(__name__)


# Grok image list prices per upstream OpenMAIC docstring (as of 2025-Q4):
#   grok-imagine-image      → $0.02 / image (standard quality)
#   grok-imagine-image-pro  → $0.07 / image (pro quality)
# xAI's pricing page is not as stable as OpenAI's; treat these as
# estimates only. Unknown model → return None (we never fabricate).
_GROK_IMAGE_PRICES_USD: dict[str, float] = {
    "grok-imagine-image": 0.02,
    "grok-imagine-image-pro": 0.07,
}


@register_adapter
class GrokImageAdapter(MediaProviderAdapter):
    """xAI Grok Images API adapter.

    Reads from TenantAIConfig:
        image_api_key (decrypted) — required; MaicConfigError if missing
        image_base_url — optional; defaults to https://api.x.ai/v1
        image_model — optional; defaults to "grok-imagine-image"

    Returns an ImageGenerationResult with a URL pointing to OUR storage
    (not xAI's CDN). We always re-host the generated image so it doesn't
    disappear when Grok rotates their CDN URLs.
    """

    name: ClassVar[str] = "grok"
    kind: ClassVar = "image"
    # Grok image latency observed at 10-30s; cap at 60s for headroom
    # (matches the OpenAI adapter — same order of magnitude).
    default_timeout_seconds: ClassVar[int] = 60

    _DEFAULT_BASE_URL: ClassVar[str] = "https://api.x.ai/v1"
    _DEFAULT_MODEL: ClassVar[str] = "grok-imagine-image"

    async def generate(self, req: ImageGenerationRequest) -> ImageGenerationResult:
        api_key = self._require_api_key()
        base_url = self._resolved_base_url()
        model = self.tenant_config.image_model or self._DEFAULT_MODEL

        # NOTE: Grok's Images API does NOT accept size/quality fields
        # — the model id alone selects standard vs pro quality. Passing
        # them would either be ignored (best case) or rejected (worst).
        # The width/height on the request are used only by the storage
        # / result layer; the upstream call shape is minimal.
        payload = {
            "model": model,
            "prompt": req.prompt,
            "n": 1,
            "response_format": "url",
        }

        # Lazy import — sys.modules patching in tests requires this. If
        # we imported aiohttp at the top of the module, tests couldn't
        # inject a fake.
        try:
            import aiohttp  # type: ignore[import-untyped]
        except ImportError as exc:
            raise MaicConfigError(
                "aiohttp is required for the Grok image adapter; "
                "pip install aiohttp"
            ) from exc

        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        }
        endpoint = f"{base_url}/images/generations"

        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(endpoint, json=payload, headers=headers) as resp:
                    body_text = await resp.text()
                    self._raise_for_status(resp.status, body_text)
                    parsed = self._parse_response_json(body_text)

                image_url = self._extract_image_url(parsed)
                content_type, image_bytes = await self._fetch_image_bytes(
                    session, image_url,
                )
        except aiohttp.ClientError as exc:
            # DNS failure, connection reset, etc. — orchestrator will retry.
            raise MaicProviderError(
                f"grok image: network error talking to {endpoint}: {exc}"
            ) from exc

        # Re-host the image in our storage so the URL outlives xAI's CDN TTL.
        media_id, stored_url = await upload_media(
            data=image_bytes,
            content_type=content_type,
            tenant_id=req.tenant_id,
            kind="image",
            scene_id=req.scene_id,
        )

        return ImageGenerationResult(
            media_id=media_id,
            url=stored_url,
            provider="grok",
            model=model,
            latency_ms=0,  # orchestrator stamps the real value
            cost_usd_estimate=self._estimate_cost(model),
        )

    # ── Internals ──────────────────────────────────────────────────────

    def _require_api_key(self) -> str:
        api_key = self.tenant_config.get_image_api_key()
        if not api_key:
            raise MaicConfigError(
                "grok image: api_key required (set image_api_key on "
                "TenantAIConfig via set_image_api_key()), or set "
                "image_provider='disabled' to skip image generation"
            )
        return api_key

    def _resolved_base_url(self) -> str:
        """Pick base URL, validate with SSRF guard if customised.

        We skip the SSRF check when the URL is the default — that's a
        well-known public endpoint, no need to DNS-resolve it twice
        per request. Custom URLs (self-hosted proxies, regional
        endpoints) MUST go through the guard."""
        raw = (self.tenant_config.image_base_url or "").strip()
        if not raw:
            return self._DEFAULT_BASE_URL.rstrip("/")
        base = raw.rstrip("/")
        if base == self._DEFAULT_BASE_URL.rstrip("/"):
            return base
        try:
            validate_webhook_host(base)
        except SSRFError as exc:
            raise MaicConfigError(
                f"grok image: image_base_url failed SSRF check: {exc}"
            ) from exc
        return base

    @staticmethod
    def _raise_for_status(status: int, body: str) -> None:
        """Translate HTTP status into typed exceptions."""
        if 200 <= status < 300:
            return
        snippet = body[:200] if body else ""
        if status in (401, 403):
            raise MaicConfigError(
                f"grok image: auth failed (HTTP {status}): {snippet}"
            )
        if status == 429:
            raise MaicProviderError(
                f"grok image: rate limited (HTTP 429): {snippet}"
            )
        if 400 <= status < 500:
            # Other 4xx — could be invalid prompt, content policy violation,
            # etc. Treat as transient; orchestrator retries with same input
            # are unlikely to succeed but the bound is small (2-3 attempts).
            raise MaicProviderError(
                f"grok image: client error (HTTP {status}): {snippet}"
            )
        # 5xx
        raise MaicProviderError(
            f"grok image: server error (HTTP {status}): {snippet}"
        )

    @staticmethod
    def _parse_response_json(body: str) -> dict:
        """Defensive JSON parse — raise MaicProviderError on malformed
        body so the orchestrator can retry."""
        import json
        try:
            return json.loads(body)
        except json.JSONDecodeError as exc:
            raise MaicProviderError(
                f"grok image: malformed JSON response: {exc}"
            ) from exc

    @staticmethod
    def _extract_image_url(data: dict) -> str:
        """Grok's response shape mirrors OpenAI:
        {data: [{url: '...', revised_prompt: '...', b64_json?: '...'}, ...]}.
        We always request n=1 so data[0] is what we want."""
        try:
            url = data["data"][0]["url"]
        except (KeyError, IndexError, TypeError) as exc:
            raise MaicProviderError(
                f"grok image: unexpected response shape: {list(data)[:5]}"
            ) from exc
        if not isinstance(url, str) or not url:
            raise MaicProviderError(
                "grok image: response had data[0].url but it was empty"
            )
        return url

    async def _fetch_image_bytes(
        self, session, image_url: str,
    ) -> tuple[str, bytes]:
        """Download the generated image from the URL Grok returned.

        Grok hosts images on a short-TTL CDN, so we always re-host
        immediately. The returned content_type comes from the CDN
        response header; default to image/png if absent."""
        async with session.get(image_url) as img_resp:
            if img_resp.status != 200:
                raise MaicProviderError(
                    f"grok image: failed to fetch generated image bytes "
                    f"(HTTP {img_resp.status})"
                )
            content_type = img_resp.headers.get("Content-Type", "image/png")
            data = await img_resp.read()
        if not data:
            raise MaicProviderError("grok image: fetched zero bytes")
        return content_type, data

    @staticmethod
    def _estimate_cost(model: str) -> float | None:
        """Flat per-image list price by model id. None for unknown
        models — we never fabricate cost numbers.

        Unlike OpenAI (price varies with size + quality), Grok's
        Images API charges a fixed per-image rate per model:
            grok-imagine-image     → $0.02
            grok-imagine-image-pro → $0.07
        """
        return _GROK_IMAGE_PRICES_USD.get(model)
