# Generated by Django 5.2.13 on 2026-05-13 06:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_calendar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calendarconnection',
            name='unique_user_provider',
        ),
        migrations.RemoveConstraint(
            model_name='calendarsyncedevent',
            name='unique_connection_source',
        ),
        migrations.AlterUniqueTogether(
            name='calendarconnection',
            unique_together={('user', 'provider')},
        ),
        migrations.AlterUniqueTogether(
            name='calendarsyncedevent',
            unique_together={('connection', 'source_type', 'source_id')},
        ),
    ]
