# Generated by Django 5.2.11 on 2026-03-26 21:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0010_tenant_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('stripe_event_id', models.CharField(help_text='Stripe event ID, e.g. evt_xxxx', max_length=255, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('payload_summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'stripe_webhook_events',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name, e.g. "Professional"', max_length=100)),
                ('plan_code', models.CharField(help_text='Internal code: FREE, STARTER, PRO, ENTERPRISE', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('price_monthly_cents', models.PositiveIntegerField(default=0)),
                ('price_yearly_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('stripe_product_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_price_monthly_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_price_yearly_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('features_json', models.JSONField(default=list, help_text='List of human-readable feature strings, e.g. ["Up to 50 teachers", "Video uploads"]')),
                ('is_custom_pricing', models.BooleanField(default=False, help_text='True for Enterprise — price negotiated per customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(db_index=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('trialing', 'Trialing'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('unpaid', 'Unpaid'), ('paused', 'Paused')], default='trialing', max_length=30)),
                ('billing_interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=10)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_invoice_id', models.CharField(max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_charge_id', models.CharField(blank=True, default='', max_length=255)),
                ('amount_cents', models.IntegerField()),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed'), ('pending', 'Pending'), ('refunded', 'Refunded')], max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('invoice_url', models.URLField(blank=True, default='', max_length=500)),
                ('invoice_pdf_url', models.URLField(blank=True, default='', max_length=500)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.tenantsubscription')),
            ],
            options={
                'db_table': 'payment_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tenantsubscription',
            index=models.Index(fields=['stripe_customer_id'], name='tenant_subs_stripe__ceb844_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantsubscription',
            index=models.Index(fields=['status'], name='tenant_subs_status_8d5eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['tenant', 'created_at'], name='payment_his_tenant__7a47c5_idx'),
        ),
    ]
