# Generated by Django 5.2.14 on 2026-07-13 03:31

from django.db import migrations, models


ENTITLEMENTS = {
    "FREE": {
        "monthly_generations": 0,
        "max_concurrent_generations": 0,
        "storage_bytes": 0,
        "max_classrooms_per_teacher": 0,
        "student_generation_enabled": False,
        "high_cost_modalities": [],
    },
    "STARTER": {
        "monthly_generations": 25,
        "max_concurrent_generations": 1,
        "storage_bytes": 5368709120,
        "max_classrooms_per_teacher": 20,
        "student_generation_enabled": False,
        "high_cost_modalities": [],
    },
    "PRO": {
        "monthly_generations": 200,
        "max_concurrent_generations": 3,
        "storage_bytes": 53687091200,
        "max_classrooms_per_teacher": 100,
        "student_generation_enabled": False,
        "high_cost_modalities": ["image"],
    },
    "ENTERPRISE": {
        "monthly_generations": 0,
        "max_concurrent_generations": 10,
        "storage_bytes": 536870912000,
        "max_classrooms_per_teacher": 0,
        "student_generation_enabled": True,
        "high_cost_modalities": ["image", "video"],
    },
}


def seed_ai_entitlements(apps, schema_editor):
    SubscriptionPlan = apps.get_model("billing", "SubscriptionPlan")
    for plan_code, entitlements in ENTITLEMENTS.items():
        SubscriptionPlan.objects.filter(plan_code=plan_code).update(
            ai_entitlements=entitlements,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_entitlements',
            field=models.JSONField(blank=True, default=dict, help_text='Machine-readable BYOK AI Classroom limits: monthly generations, concurrency, storage, student generation, and high-cost modalities.'),
        ),
        migrations.RunPython(seed_ai_entitlements, migrations.RunPython.noop),
    ]
