# Generated by Django 5.0.1 on 2026-02-16 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="webhookdelivery",
            new_name="webhook_del_endpoin_4ffb63_idx",
            old_name="whd_endpoint_status_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookdelivery",
            new_name="webhook_del_status_741062_idx",
            old_name="whd_status_retry_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookdelivery",
            new_name="webhook_del_event_t_dae0cf_idx",
            old_name="whd_event_created_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookendpoint",
            new_name="webhook_end_tenant__85ae26_idx",
            old_name="wh_tenant_active_idx",
        ),
    ]
