import type { TourRole, TourStep } from './types';

const resolveFirstSchoolPath = (): string | null => {
  const pathMatch = window.location.pathname.match(/^\/super-admin\/schools\/([^/]+)/);
  if (pathMatch?.[1]) {
    return `/super-admin/schools/${pathMatch[1]}`;
  }
  const row = document.querySelector<HTMLElement>('[data-tour="superadmin-school-row"]');
  const tenantId = row?.dataset.tenantId;
  return tenantId ? `/super-admin/schools/${tenantId}` : null;
};

const resolveFirstTeacherCoursePath = (): string | null => {
  const pathMatch = window.location.pathname.match(/^\/teacher\/courses\/([^/]+)/);
  if (pathMatch?.[1]) {
    return `/teacher/courses/${pathMatch[1]}`;
  }
  const card = document.querySelector<HTMLElement>('[data-tour="teacher-course-card"]');
  const courseId = card?.dataset.courseId;
  return courseId ? `/teacher/courses/${courseId}` : null;
};

const superAdminSteps: TourStep[] = [
  {
    id: 'sa-sidebar',
    title: 'Command Navigation',
    description: 'Use this sidebar to move across the full platform command center.',
    path: '/super-admin/dashboard',
    selector: '[data-tour="superadmin-sidebar"]',
    placement: 'right',
  },
  {
    id: 'sa-onboard',
    title: 'Onboard New School',
    description: 'Start a new tenant setup from this action. It is the fastest path to launch a school.',
    path: '/super-admin/dashboard',
    selector: '[data-tour="superadmin-dashboard-onboard"]',
    placement: 'bottom',
  },
  {
    id: 'sa-stats',
    title: 'Platform Health Snapshot',
    description: 'These cards summarize schools, users, and trial status at a glance.',
    path: '/super-admin/dashboard',
    selector: '[data-tour="superadmin-dashboard-stats"]',
    placement: 'bottom',
  },
  {
    id: 'sa-plan-distribution',
    title: 'Plan Mix',
    description: 'Track subscription distribution so you can monitor plan adoption trends.',
    path: '/super-admin/dashboard',
    selector: '[data-tour="superadmin-dashboard-plan-distribution"]',
    placement: 'left',
  },
  {
    id: 'sa-recent-onboards',
    title: 'Recent School Onboards',
    description: 'Jump directly to the latest schools and inspect their setup quickly.',
    path: '/super-admin/dashboard',
    selector: '[data-tour="superadmin-dashboard-recent-onboards"]',
    placement: 'left',
  },
  {
    id: 'sa-near-limits',
    title: 'Limit Alerts',
    description: 'Review schools approaching limits so you can intervene before disruption.',
    path: '/super-admin/dashboard',
    selector: '[data-tour="superadmin-dashboard-near-limits"]',
    placement: 'left',
  },
  {
    id: 'sa-schools-nav',
    title: 'Schools Workspace',
    description: 'Now we move to the Schools workspace for full tenant-level operations.',
    path: '/super-admin/schools',
    selector: '[data-tour="superadmin-nav-schools"]',
    placement: 'right',
  },
  {
    id: 'sa-schools-search',
    title: 'School Search',
    description: 'Filter schools by name or subdomain to find the exact tenant instantly.',
    path: '/super-admin/schools',
    selector: '[data-tour="superadmin-schools-search"]',
    placement: 'bottom',
  },
  {
    id: 'sa-schools-table',
    title: 'Tenant Operations Table',
    description: 'This table is your control plane for status, usage signals, and quick actions.',
    path: '/super-admin/schools',
    selector: '[data-tour="superadmin-schools-table"]',
    placement: 'top',
  },
  {
    id: 'sa-schools-onboard-btn',
    title: 'Launch Onboarding Flow',
    description: 'This button opens the onboarding form from the Schools page as well.',
    path: '/super-admin/schools',
    selector: '[data-tour="superadmin-schools-onboard"]',
    placement: 'left',
  },
  {
    id: 'sa-school-detail-header',
    title: 'School Detail Console',
    description: 'Open any school row to enter this detailed management console.',
    path: resolveFirstSchoolPath,
    fallbackPath: '/super-admin/schools',
    selector: '[data-tour="superadmin-school-header"]',
    placement: 'bottom',
    optional: true,
    pathMatch: 'startsWith',
    waitMs: 8000,
  },
  {
    id: 'sa-school-tabs',
    title: 'Overview, Plan, Features',
    description: 'These tabs split tenant management into lifecycle overview, limits, and feature controls.',
    path: resolveFirstSchoolPath,
    fallbackPath: '/super-admin/schools',
    selector: '[data-tour="superadmin-school-tabs"]',
    placement: 'bottom',
    optional: true,
    pathMatch: 'startsWith',
    waitMs: 7000,
  },
  {
    id: 'sa-school-overview',
    title: 'Usage Visibility',
    description: 'Monitor consumption and notes to make support and commercial decisions quickly.',
    path: () => {
      const base = resolveFirstSchoolPath();
      return base ? `${base}?tab=overview` : null;
    },
    fallbackPath: '/super-admin/schools',
    selector: '[data-tour="superadmin-school-overview-usage"]',
    placement: 'right',
    optional: true,
    pathMatch: 'startsWith',
    waitMs: 7000,
  },
  {
    id: 'sa-school-plan',
    title: 'Plan and Limits Control',
    description: 'Adjust plan presets and hard limits from this panel.',
    path: () => {
      const base = resolveFirstSchoolPath();
      return base ? `${base}?tab=plan` : null;
    },
    fallbackPath: '/super-admin/schools',
    selector: '[data-tour="superadmin-school-plan-card"]',
    placement: 'top',
    optional: true,
    pathMatch: 'startsWith',
    waitMs: 7000,
  },
  {
    id: 'sa-school-features',
    title: 'Feature Flags',
    description: 'Toggle tenant capabilities here, with immediate impact per school.',
    path: () => {
      const base = resolveFirstSchoolPath();
      return base ? `${base}?tab=features` : null;
    },
    fallbackPath: '/super-admin/schools',
    selector: '[data-tour="superadmin-school-features-grid"]',
    placement: 'top',
    optional: true,
    pathMatch: 'startsWith',
    waitMs: 7000,
  },
  {
    id: 'sa-replay',
    title: 'Replay Anytime',
    description: 'Use this quick action whenever you want to run the super-admin tour again.',
    path: '/super-admin/schools',
    selector: '[data-tour="superadmin-tour-replay"]',
    placement: 'right',
  },
];

const adminSteps: TourStep[] = [
  {
    id: 'admin-sidebar',
    title: 'Admin Navigation',
    description: 'This sidebar is your primary command surface for school operations.',
    path: '/admin/dashboard',
    selector: '[data-tour="admin-sidebar"]',
    placement: 'right',
  },
  {
    id: 'admin-dashboard-hero',
    title: 'Daily Command Header',
    description: 'Use this header to orient quickly and launch common actions immediately.',
    path: '/admin/dashboard',
    selector: '[data-tour="admin-dashboard-hero"]',
    placement: 'bottom',
  },
  {
    id: 'admin-dashboard-stats',
    title: 'Core Metrics',
    description: 'These metrics track teacher activity, course performance, and review load.',
    path: '/admin/dashboard',
    selector: '[data-tour="admin-dashboard-stats"]',
    placement: 'bottom',
  },
  {
    id: 'admin-dashboard-activity',
    title: 'Activity Timeline',
    description: 'Review recent completion events and spot momentum or gaps quickly.',
    path: '/admin/dashboard',
    selector: '[data-tour="admin-dashboard-activity"]',
    placement: 'right',
  },
  {
    id: 'admin-dashboard-actions',
    title: 'Quick Actions',
    description: 'Use these shortcuts to create courses, add teachers, and jump to key workflows.',
    path: '/admin/dashboard',
    selector: '[data-tour="admin-dashboard-quick-actions"]',
    placement: 'top',
  },
  {
    id: 'admin-courses-nav',
    title: 'Courses',
    description: 'Next we move into Courses to manage structure, publishing, and assignments.',
    path: '/admin/courses',
    selector: '[data-tour="admin-nav-courses"]',
    placement: 'right',
  },
  {
    id: 'admin-courses-filters',
    title: 'Course Filters and Views',
    description: 'Filter by status/type and switch table or board mode for faster operations.',
    path: '/admin/courses',
    selector: '[data-tour="admin-courses-filters"]',
    placement: 'bottom',
  },
  {
    id: 'admin-courses-list',
    title: 'Course Inventory',
    description: 'Manage each course lifecycle here: publish, edit, duplicate, and remove.',
    path: '/admin/courses',
    selector: '[data-tour="admin-courses-list"]',
    placement: 'top',
  },
  {
    id: 'admin-courses-create',
    title: 'Create Course',
    description: 'Create a new course from this action and move into the editor flow.',
    path: '/admin/courses',
    selector: '[data-tour="admin-courses-create"]',
    placement: 'left',
  },
  {
    id: 'admin-course-editor-tabs',
    title: 'Course Editor Tabs',
    description: 'Build courses in order: details first, then content, then assignment targeting.',
    path: '/admin/courses/new?tab=details',
    selector: '[data-tour="admin-course-editor-tabs"]',
    placement: 'bottom',
    waitMs: 7000,
  },
  {
    id: 'admin-course-editor-details',
    title: 'Details Setup',
    description: 'Set title, description, timeline, and thumbnail in this panel.',
    path: '/admin/courses/new?tab=details',
    selector: '[data-tour="admin-course-details-panel"]',
    placement: 'right',
    waitMs: 7000,
  },
  {
    id: 'admin-course-editor-content',
    title: 'Content Builder',
    description: 'Once saved, use this tab to create modules and add videos, docs, links, and text.',
    path: '/admin/courses/new?tab=details',
    selector: '[data-tour="admin-course-content-panel"]',
    placement: 'top',
    optional: true,
    waitMs: 8000,
  },
  {
    id: 'admin-course-editor-assignment',
    title: 'Assignment Targeting',
    description: 'Control whether a course goes to all teachers, groups, or specific people.',
    path: '/admin/courses/new?tab=assignment',
    selector: '[data-tour="admin-course-assignment-panel"]',
    placement: 'top',
    waitMs: 7000,
  },
  {
    id: 'admin-media',
    title: 'Media Library',
    description: 'Upload and manage reusable media assets for all courses.',
    path: '/admin/media',
    selector: '[data-tour="admin-media-grid"]',
    placement: 'top',
  },
  {
    id: 'admin-teachers',
    title: 'Teacher Management',
    description: 'Search, bulk update, import, and manage teacher lifecycle in this workspace.',
    path: '/admin/teachers',
    selector: '[data-tour="admin-teachers-table"]',
    placement: 'top',
  },
  {
    id: 'admin-groups',
    title: 'Groups',
    description: 'Create teacher cohorts and maintain their members for targeted delivery.',
    path: '/admin/groups',
    selector: '[data-tour="admin-groups-members"]',
    placement: 'top',
    optional: true,
  },
  {
    id: 'admin-reminders',
    title: 'Reminders',
    description: 'Compose and send reminder campaigns with preview and history tracking.',
    path: '/admin/reminders',
    selector: '[data-tour="admin-reminders-composer"]',
    placement: 'right',
    optional: true,
  },
  {
    id: 'admin-announcements',
    title: 'Announcements',
    description: 'Publish school-wide or group-targeted updates from this broadcast panel.',
    path: '/admin/announcements',
    selector: '[data-tour="admin-announcements-compose"]',
    placement: 'right',
  },
  {
    id: 'admin-analytics',
    title: 'Analytics',
    description: 'Analyze engagement, completion, and department-level trends here.',
    path: '/admin/analytics',
    selector: '[data-tour="admin-analytics-summary"]',
    placement: 'bottom',
  },
  {
    id: 'admin-settings',
    title: 'Brand Settings',
    description: 'Manage school branding, colors, and visual identity in this page.',
    path: '/admin/settings',
    selector: '[data-tour="admin-settings-branding"]',
    placement: 'top',
  },
  {
    id: 'admin-security',
    title: 'Security Controls',
    description: 'Configure 2FA and SSO from the security section.',
    path: '/admin/settings/security',
    selector: '[data-tour="security-2fa-section"]',
    placement: 'top',
  },
  {
    id: 'admin-replay',
    title: 'Replay Anytime',
    description: 'Use this quick action whenever you want to run the admin tour again.',
    path: '/admin/dashboard',
    selector: '[data-tour="admin-tour-replay"]',
    placement: 'right',
  },
];

const teacherSteps: TourStep[] = [
  {
    id: 'teacher-sidebar',
    title: 'Teacher Navigation',
    description: 'This sidebar gives quick access to daily teacher workflows.',
    path: '/teacher/dashboard',
    selector: '[data-tour="teacher-sidebar"]',
    placement: 'right',
  },
  {
    id: 'teacher-dashboard-stats',
    title: 'Progress Snapshot',
    description: 'Use these cards to monitor progress, completions, and pending work.',
    path: '/teacher/dashboard',
    selector: '[data-tour="teacher-dashboard-stats"]',
    placement: 'bottom',
  },
  {
    id: 'teacher-dashboard-continue',
    title: 'Continue Learning',
    description: 'Resume learning directly from your most relevant course.',
    path: '/teacher/dashboard',
    selector: '[data-tour="teacher-dashboard-continue"]',
    placement: 'top',
  },
  {
    id: 'teacher-dashboard-deadlines',
    title: 'Upcoming Deadlines',
    description: 'Track urgent course and assignment deadlines in one place.',
    path: '/teacher/dashboard',
    selector: '[data-tour="teacher-dashboard-deadlines"]',
    placement: 'left',
  },
  {
    id: 'teacher-courses',
    title: 'My Courses',
    description: 'Browse all assigned courses and filter by status from this page.',
    path: '/teacher/courses',
    selector: '[data-tour="teacher-courses-grid"]',
    placement: 'top',
  },
  {
    id: 'teacher-courses-filters',
    title: 'Course Filters',
    description: 'Use search and status filters to quickly find the right course.',
    path: '/teacher/courses',
    selector: '[data-tour="teacher-courses-filters"]',
    placement: 'bottom',
  },
  {
    id: 'teacher-course-view',
    title: 'Course Player',
    description: 'Open any course card to study content and track completion live.',
    path: resolveFirstTeacherCoursePath,
    fallbackPath: '/teacher/courses',
    selector: '[data-tour="teacher-course-player"]',
    placement: 'top',
    optional: true,
    pathMatch: 'startsWith',
    waitMs: 12000,
  },
  {
    id: 'teacher-course-structure',
    title: 'Module Navigator',
    description: 'Use this side panel to move lesson-by-lesson and monitor completion.',
    path: resolveFirstTeacherCoursePath,
    fallbackPath: '/teacher/courses',
    selector: '[data-tour="teacher-course-structure"]',
    placement: 'left',
    optional: true,
    pathMatch: 'startsWith',
    waitMs: 10000,
  },
  {
    id: 'teacher-assignments',
    title: 'Assignments',
    description: 'Track pending and submitted assignments, including quizzes.',
    path: '/teacher/assignments',
    selector: '[data-tour="teacher-assignments-list"]',
    placement: 'top',
  },
  {
    id: 'teacher-reminders',
    title: 'Reminders Inbox',
    description: 'Read, filter, and mark reminders as done from this dedicated inbox.',
    path: '/teacher/reminders',
    selector: '[data-tour="teacher-reminders-list"]',
    placement: 'top',
  },
  {
    id: 'teacher-profile',
    title: 'Profile and Preferences',
    description: 'Manage profile details, password, and notification settings here.',
    path: '/teacher/profile',
    selector: '[data-tour="teacher-profile-sections"]',
    placement: 'right',
  },
  {
    id: 'teacher-replay',
    title: 'Replay Anytime',
    description: 'Use this quick action whenever you want to run the teacher tour again.',
    path: '/teacher/profile',
    selector: '[data-tour="teacher-profile-tour-replay"]',
    placement: 'bottom',
  },
];

export const TOUR_STEPS: Record<TourRole, TourStep[]> = {
  SUPER_ADMIN: superAdminSteps,
  SCHOOL_ADMIN: adminSteps,
  TEACHER: teacherSteps,
};
