# Generated by Django 5.2.13 on 2026-05-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_builder', '0002_reportrun_artifact_format'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportdefinition',
            new_name='report_defi_tenant__bb9d1c_idx',
            old_name='report_def_tenant_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='reportdefinition',
            new_name='report_defi_tenant__ac60aa_idx',
            old_name='report_def_tenant_source_idx',
        ),
        migrations.RenameIndex(
            model_name='reportdefinition',
            new_name='report_defi_created_6978e7_idx',
            old_name='report_def_created_by_idx',
        ),
        migrations.RenameIndex(
            model_name='reportrun',
            new_name='report_runs_tenant__75e051_idx',
            old_name='report_run_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reportrun',
            new_name='report_runs_tenant__ed1b9b_idx',
            old_name='report_run_tenant_def_started_idx',
        ),
        migrations.RenameIndex(
            model_name='reportrun',
            new_name='report_runs_run_by__460008_idx',
            old_name='report_run_run_by_idx',
        ),
        migrations.RenameIndex(
            model_name='reportschedule',
            new_name='report_sche_tenant__f19cba_idx',
            old_name='report_sched_tenant_enabled_idx',
        ),
        migrations.RenameIndex(
            model_name='reportschedule',
            new_name='report_sche_definit_74e969_idx',
            old_name='report_sched_definition_idx',
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='last_run_status',
            field=models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('never_run', 'Never Run'), ('delivery_failed', 'Delivery Failed')], default='never_run', max_length=20),
        ),
    ]
