"""MAIC v2 models.

Phase 0 ships only `MaicSessionV2` — the minimal session pointer that the
WS consumer (MAIC-003) and the HTTP session route (Phase 1, MAIC-301)
use as a stable identifier. Richer state (scenes, agent configs,
generated content) lives in Phase 1+ models that FK to this one.

Tenant isolation: every row is tenant-scoped via TenantManager. There is
no notion of a global classroom; cross-tenant access is denied at the
queryset level.
"""
from __future__ import annotations

from django.conf import settings
from django.db import models

from apps.tenants.models import Tenant
from apps.courses.models import Course
from utils.tenant_manager import TenantManager


class MaicSessionV2(models.Model):
    """Live AI Classroom session (one per tenant + course + opener).

    Held minimal in Phase 0; Phase 1's MAIC-301 adds `agent_ids`,
    `language`, `level`, `topic` columns and the start-of-session
    snapshot fields.
    """

    id = models.CharField(primary_key=True, max_length=64)
    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE, db_index=True)
    course = models.ForeignKey(
        Course, on_delete=models.SET_NULL, null=True, blank=True, db_index=True
    )
    opened_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="maic_v2_sessions_opened",
    )
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    last_event_at = models.DateTimeField(auto_now=True)

    objects = TenantManager()

    class Meta:
        db_table = "maic_session_v2"
        indexes = [
            models.Index(fields=["tenant", "created_at"]),
        ]
        verbose_name = "MAIC v2 session"
        verbose_name_plural = "MAIC v2 sessions"

    def __str__(self) -> str:  # pragma: no cover — repr only
        return f"MaicSessionV2(id={self.id}, tenant={self.tenant_id})"


class MaicGenerationJob(models.Model):
    """Persistent state for a v2 generation run (Phase 4 Session 6).

    Lifecycle:
      HTTP POST /api/maic/v2/generate/  → row inserted, status=pending
      Celery outline_task               → status=in_progress, stage=1
      Celery scene_dispatch_task        → stage=2 + per-scene increments
      Celery finalize_task              → status=succeeded, result set
      Any task failure                  → status=failed, error populated

    The WS consumer (MAIC-428.3) streams progress events out-of-band
    via channel_layer.group_send from the worker, but this row is the
    canonical source of truth — the consumer hydrates initial state
    from this row when a client connects mid-run.

    `id` is a 12-char URL-safe nanoid generated by
    pipeline_runner.create_generation_session — re-used as the WS
    job_id so clients can pair the HTTP POST response with the WS
    subscription deterministically.
    """

    STATUS_PENDING = "pending"
    STATUS_IN_PROGRESS = "in_progress"
    STATUS_SUCCEEDED = "succeeded"
    STATUS_FAILED = "failed"
    STATUS_CHOICES = [
        (STATUS_PENDING, "Pending"),
        (STATUS_IN_PROGRESS, "In progress"),
        (STATUS_SUCCEEDED, "Succeeded"),
        (STATUS_FAILED, "Failed"),
    ]

    id = models.CharField(primary_key=True, max_length=32)
    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE, db_index=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="maic_v2_generation_jobs",
    )
    requirements = models.JSONField(default=dict)
    status = models.CharField(
        max_length=16, choices=STATUS_CHOICES, default=STATUS_PENDING,
        db_index=True,
    )
    progress = models.JSONField(default=dict)
    result = models.JSONField(default=dict)
    error = models.TextField(blank=True, default="")

    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    objects = TenantManager()

    class Meta:
        db_table = "maic_generation_job"
        indexes = [
            models.Index(fields=["tenant", "created_at"]),
            models.Index(fields=["status"]),
        ]
        verbose_name = "MAIC v2 generation job"
        verbose_name_plural = "MAIC v2 generation jobs"

    def __str__(self) -> str:  # pragma: no cover — repr only
        return f"MaicGenerationJob(id={self.id}, status={self.status})"
