# Generated by Django 5.2.11 on 2026-04-12 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0013_initial_academic_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Early Years, Primary, High School', max_length=100)),
                ('short_code', models.CharField(help_text='e.g. KEY, PRI, MID, HS', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order across grade bands')),
                ('curriculum_framework', models.CharField(choices=[('REGGIO_EMILIA', 'Reggio Emilia'), ('CAMBRIDGE_PRIMARY', 'Cambridge Primary'), ('CAMBRIDGE_SECONDARY', 'Cambridge Secondary'), ('IGCSE', 'IGCSE'), ('KIPP', 'KIPP'), ('IB', 'International Baccalaureate'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=30)),
                ('theme_config', models.JSONField(blank=True, default=None, help_text='Optional per-band theming: {"accent_color": "#hex", "bg_image": "url", "welcome_msg": "text"}', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_bands', to='tenants.tenant')),
            ],
            options={
                'db_table': 'grade_bands',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Nursery, PP1, Grade 9', max_length=50)),
                ('short_code', models.CharField(help_text='e.g. NUR, PP1, G9', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Global sort order across all grade bands')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='tenants.tenant')),
                ('grade_band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.gradeband')),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. A, B, C', max_length=20)),
                ('academic_year', models.CharField(help_text='e.g. 2026-27', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_teacher', models.ForeignKey(blank=True, help_text='Teacher assigned as class teacher for this section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_sections', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.grade')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['grade__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Physics, English Language', max_length=100)),
                ('code', models.CharField(help_text='e.g. PHY, ENG', max_length=20)),
                ('department', models.CharField(blank=True, default='', help_text='e.g. Science, Languages, Commerce', max_length=100)),
                ('is_elective', models.BooleanField(default=False, help_text='Is this an elective subject?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_grades', models.ManyToManyField(blank=True, help_text='Which grades this subject is taught in', related_name='subjects', to='academics.grade')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='tenants.tenant')),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(help_text='e.g. 2026-27', max_length=20)),
                ('is_class_teacher', models.BooleanField(default=False, help_text='Whether this teacher is the class teacher for assigned sections')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sections', models.ManyToManyField(blank=True, help_text='Sections this teacher teaches this subject in', related_name='teaching_assignments', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'teaching_assignments',
                'ordering': ['teacher__last_name', 'subject__name'],
            },
        ),
        migrations.AddIndex(
            model_name='gradeband',
            index=models.Index(fields=['tenant', 'order'], name='grade_bands_tenant__ccb806_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradeband',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['tenant', 'order'], name='grades_tenant__f21abc_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['tenant', 'grade_band'], name='grades_tenant__793ba1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('tenant', 'short_code')},
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['tenant', 'academic_year'], name='sections_tenant__9d71f2_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['tenant', 'grade', 'academic_year'], name='sections_tenant__14b123_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('tenant', 'grade', 'name', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['tenant', 'department'], name='subjects_tenant__61c53d_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['tenant', 'is_elective'], name='subjects_tenant__31547c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='teachingassignment',
            index=models.Index(fields=['tenant', 'academic_year'], name='teaching_as_tenant__9d9e20_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingassignment',
            index=models.Index(fields=['tenant', 'teacher', 'academic_year'], name='teaching_as_tenant__badf79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together={('tenant', 'teacher', 'subject', 'academic_year')},
        ),
    ]
