# Generated by Django 5.2.13 on 2026-05-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_attendance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendance_tenant__e63c6a_idx',
            old_name='attendance_tenant__1a9b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendance_tenant__3b4417_idx',
            old_name='attendance_tenant__3d4e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendance_tenant__3f1926_idx',
            old_name='attendance_tenant__6g7h8i_idx',
        ),
    ]
