# Generated by Django 5.0.1 on 2026-02-02 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="assigned_teachers",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_courses", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="courses.module",
            ),
        ),
        migrations.AddField(
            model_name="teachergroup",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_groups",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="assigned_groups",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="courses.teachergroup"
            ),
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(
                fields=["course", "order"], name="modules_course__4500e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["module", "order"], name="contents_module__f49825_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teachergroup",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["tenant", "is_published"], name="courses_tenant__07b669_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["tenant", "is_mandatory"], name="courses_tenant__2d91cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["deadline"], name="courses_deadlin_9f7e41_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("tenant", "slug")},
        ),
    ]
