# Generated by GPT-5.2 on 2026-02-04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoAsset",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("source_file", models.CharField(blank=True, default="", max_length=512)),
                ("source_url", models.URLField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("PROCESSING", "Processing"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("codec", models.CharField(blank=True, default="", max_length=64)),
                ("hls_master_url", models.URLField(blank=True, default="")),
                ("thumbnail_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_asset",
                        to="courses.content",
                    ),
                ),
            ],
            options={
                "db_table": "video_assets",
            },
        ),
        migrations.CreateModel(
            name="VideoTranscript",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("language", models.CharField(default="en", max_length=20)),
                ("full_text", models.TextField(blank=True, default="")),
                ("segments", models.JSONField(blank=True, default=list)),
                ("vtt_url", models.URLField(blank=True, default="")),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video_asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript",
                        to="courses.videoasset",
                    ),
                ),
            ],
            options={
                "db_table": "video_transcripts",
            },
        ),
        migrations.AddIndex(
            model_name="videoasset",
            index=models.Index(fields=["status"], name="video_assets_status_idx"),
        ),
        migrations.AddIndex(
            model_name="videoasset",
            index=models.Index(fields=["content"], name="video_assets_content_idx"),
        ),
    ]

