# Generated by Django 5.0.1 on 2026-02-08 00:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_video_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="videoasset",
            new_name="video_asset_status_5df695_idx",
            old_name="video_assets_status_idx",
        ),
        migrations.RenameIndex(
            model_name="videoasset",
            new_name="video_asset_content_94f546_idx",
            old_name="video_assets_content_idx",
        ),
    ]
