# Generated by Django 5.0.1 on 2026-02-08 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0004_rename_video_assets_status_idx_video_asset_status_5df695_idx_and_more",
        ),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="media_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Source media asset from the library (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_contents",
                to="media.mediaasset",
            ),
        ),
    ]
