# Generated by Django 5.0.1 on 2026-02-15 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_learning_paths"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="course",
            name="courses_tenant__07b669_idx",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="courses_tenant__2d91cb_idx",
        ),
        migrations.RenameIndex(
            model_name="course",
            new_name="courses_tenant__c12868_idx",
            old_name="courses_tenant_pub_active_idx",
        ),
        migrations.RenameIndex(
            model_name="course",
            new_name="courses_tenant__39c4bb_idx",
            old_name="courses_tenant_mand_active_idx",
        ),
        migrations.RenameIndex(
            model_name="course",
            new_name="courses_tenant__f2ac05_idx",
            old_name="courses_tenant_created_idx",
        ),
        migrations.RenameIndex(
            model_name="learningpath",
            new_name="learning_pa_tenant__77661b_idx",
            old_name="lp_tenant_pub_active_idx",
        ),
        migrations.RenameIndex(
            model_name="learningpathcourse",
            new_name="learning_pa_learnin_34b286_idx",
            old_name="lpc_path_order_idx",
        ),
        migrations.RenameIndex(
            model_name="learningpathprogress",
            new_name="learning_pa_teacher_3cd120_idx",
            old_name="lpp_teacher_status_idx",
        ),
        migrations.RenameIndex(
            model_name="learningpathprogress",
            new_name="learning_pa_learnin_b563c0_idx",
            old_name="lpp_path_status_idx",
        ),
    ]
