# Generated by Django 5.2.11 on 2026-02-21 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_assignment_soft_delete_fields'),
        ('tenants', '0007_tenant_feature_teacher_authoring'),
        ('users', '0003_add_teacher_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichTextImageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rich_text_images', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_rich_text_images', to='users.user')),
            ],
            options={
                'db_table': 'rich_text_image_assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='richtextimageasset',
            index=models.Index(fields=['tenant', 'created_at'], name='rich_text_i_tenant__183a54_idx'),
        ),
        migrations.AddIndex(
            model_name='richtextimageasset',
            index=models.Index(fields=['tenant', 'storage_key'], name='rich_text_i_tenant__25bf38_idx'),
        ),
    ]
