# Generated by Django 5.2.11 on 2026-02-27 00:18

import utils.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rich_text_image_assets'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='richtextimageasset',
            new_name='rich_text_i_tenant__b2415b_idx',
            old_name='rich_text_i_tenant__183a54_idx',
        ),
        migrations.RenameIndex(
            model_name='richtextimageasset',
            new_name='rich_text_i_tenant__f159d4_idx',
            old_name='rich_text_i_tenant__25bf38_idx',
        ),
        migrations.RemoveField(
            model_name='content',
            name='media_asset',
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.storage_paths.course_thumbnail_upload_to),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.storage_paths.learning_path_thumbnail_upload_to),
        ),
    ]
