# Generated by Django 5.2.11 on 2026-04-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_action_plan'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='actionplan',
            new_name='action_plan_tenant__22ecea_idx',
            old_name='action_plan_tenant__d1e2f3_idx',
        ),
        migrations.RenameIndex(
            model_name='actionplan',
            new_name='action_plan_tenant__300752_idx',
            old_name='action_plan_tenant__g4h5i6_idx',
        ),
        migrations.RenameIndex(
            model_name='interactivelesson',
            new_name='interactive_tenant__135dc9_idx',
            old_name='interactiv_tenant__e1a2b3_idx',
        ),
        migrations.RenameIndex(
            model_name='interactivelesson',
            new_name='interactive_tenant__d3ffd0_idx',
            old_name='interactiv_tenant__f4g5h6_idx',
        ),
        migrations.RenameIndex(
            model_name='lessonreflectionresponse',
            new_name='lesson_refl_tenant__4733f3_idx',
            old_name='lesson_ref_tenant__y2z3a4_idx',
        ),
        migrations.RenameIndex(
            model_name='scenarioattempt',
            new_name='scenario_at_tenant__9343ea_idx',
            old_name='scenario_a_tenant__s6t7u8_idx',
        ),
        migrations.RenameIndex(
            model_name='scenarioattempt',
            new_name='scenario_at_tenant__b08b96_idx',
            old_name='scenario_a_tenant__v9w0x1_idx',
        ),
        migrations.RenameIndex(
            model_name='scenariotemplate',
            new_name='scenario_te_tenant__2a112f_idx',
            old_name='scenario_t_tenant__j7k8l9_idx',
        ),
        migrations.RenameIndex(
            model_name='scenariotemplate',
            new_name='scenario_te_tenant__5abea7_idx',
            old_name='scenario_t_tenant__m0n1o2_idx',
        ),
        migrations.RenameIndex(
            model_name='scenariotemplate',
            new_name='scenario_te_tenant__8845ae_idx',
            old_name='scenario_t_tenant__p3q4r5_idx',
        ),
        migrations.RenameIndex(
            model_name='teachingstrategy',
            new_name='teaching_st_tenant__62e730_idx',
            old_name='teaching_st_tenant__a1b2c3_idx',
        ),
        migrations.AddField(
            model_name='interactivelesson',
            name='generation_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interactivelesson',
            name='has_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interactivelesson',
            name='image_generation_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial_failure', 'Partial Failure')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='interactivelesson',
            name='lesson_format',
            field=models.CharField(choices=[('text', 'Text'), ('visual', 'Visual')], default='visual', max_length=10),
        ),
        migrations.AddField(
            model_name='interactivelesson',
            name='scene_schema_version',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='lessonreflectionresponse',
            name='scene_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
