# Generated by Django 5.2.11 on 2026-04-08 05:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0017_lessonquizresponse"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="lessonquizresponse",
            new_name="lesson_quiz_tenant__54d9b8_idx",
            old_name="lesson_quiz_tenant__idx",
        ),
    ]
