# Generated by Django 5.2.11 on 2026-04-11 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_quiz_response_model'),
        ('tenants', '0012_tenant_feature_students_tenant_max_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, help_text='Individual students assigned to this course', limit_choices_to={'role': 'STUDENT'}, related_name='student_assigned_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='assigned_to_all_students',
            field=models.BooleanField(default=False, help_text='Assign to all students in tenant'),
        ),
        migrations.CreateModel(
            name='AIPersonaSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('persona_type', models.CharField(choices=[('TEACHER', 'Teacher'), ('TA', 'Teaching Assistant'), ('STUDY_BUDDY', 'Study Buddy'), ('SOCRATIC', 'Socratic Tutor')], max_length=20)),
                ('title', models.CharField(blank=True, help_text='Auto-generated from first message or manually set', max_length=300)),
                ('context_content_id', models.UUIDField(blank=True, help_text='Content being studied when session started', null=True)),
                ('context_summary', models.TextField(blank=True, default='', help_text='Summary of course content for AI context')),
                ('is_active', models.BooleanField(default=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_persona_sessions', to='courses.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_persona_sessions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_persona_sessions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ai_persona_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPersonaMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='courses.aipersonasession')),
            ],
            options={
                'db_table': 'ai_persona_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=10)),
                ('shared_notes', models.JSONField(blank=True, default=list)),
                ('activity_feed', models.JSONField(blank=True, default=list, help_text='List of {type, user_name, message, timestamp}')),
                ('max_participants', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_sessions', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classroom_sessions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_sessions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'classroom_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('FACILITATOR', 'Facilitator')], default='MEMBER', max_length=15)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_participations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='courses.classroomsession')),
            ],
            options={
                'db_table': 'classroom_participants',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='CoursePodcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('style', models.CharField(choices=[('CONVERSATIONAL', 'Conversational (two hosts)'), ('LECTURE', 'Lecture (single narrator)'), ('INTERVIEW', 'Interview (host + expert)'), ('DEEP_DIVE', 'Deep Dive (detailed analysis)')], default='CONVERSATIONAL', max_length=20)),
                ('script', models.JSONField(blank=True, default=list)),
                ('audio_url', models.CharField(blank=True, default='', max_length=512)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('source_text', models.TextField(blank=True, default='', help_text='Aggregated course text used as LLM input')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING_SCRIPT', 'Generating Script'), ('GENERATING_AUDIO', 'Generating Audio'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('generation_model', models.CharField(blank=True, default='', max_length=100)),
                ('tts_provider', models.CharField(blank=True, default='', max_length=50)),
                ('error_message', models.TextField(blank=True, default='')),
                ('generation_metadata', models.JSONField(blank=True, default=dict)),
                ('estimated_minutes', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(blank=True, help_text='If set, podcast covers only this content item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='courses.content')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_podcasts', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, help_text='If set, podcast covers only this module', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='courses.module')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_podcasts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'course_podcasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyNotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('COURSE', 'Entire Course'), ('MODULE', 'Single Module'), ('CONTENT', 'Single Content Item')], default='MODULE', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('full_markdown', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('generation_model', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_notes', to='courses.content')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_notes', to='courses.course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_notes', to='courses.module')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_notes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_notes', to='tenants.tenant')),
            ],
            options={
                'db_table': 'study_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aipersonasession',
            index=models.Index(fields=['tenant', 'teacher', 'course', '-updated_at'], name='ai_persona__tenant__e6d84c_idx'),
        ),
        migrations.AddIndex(
            model_name='aipersonasession',
            index=models.Index(fields=['tenant', 'teacher', 'persona_type'], name='ai_persona__tenant__77c8dc_idx'),
        ),
        migrations.AddIndex(
            model_name='aipersonasession',
            index=models.Index(fields=['tenant', 'teacher', 'is_active'], name='ai_persona__tenant__78204f_idx'),
        ),
        migrations.AddIndex(
            model_name='aipersonamessage',
            index=models.Index(fields=['session', 'created_at'], name='ai_persona__session_45534b_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomsession',
            index=models.Index(fields=['tenant', 'course', 'status'], name='classroom_s_tenant__c5e6c6_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomsession',
            index=models.Index(fields=['tenant', 'status', '-updated_at'], name='classroom_s_tenant__693b20_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomparticipant',
            index=models.Index(fields=['session', 'role'], name='classroom_p_session_e48a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomparticipant',
            index=models.Index(fields=['teacher', 'last_active_at'], name='classroom_p_teacher_aebb17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroomparticipant',
            unique_together={('session', 'teacher')},
        ),
        migrations.AddIndex(
            model_name='coursepodcast',
            index=models.Index(fields=['tenant', 'course', 'status'], name='course_podc_tenant__dfa6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='coursepodcast',
            index=models.Index(fields=['tenant', 'status'], name='course_podc_tenant__92fe59_idx'),
        ),
        migrations.AddIndex(
            model_name='coursepodcast',
            index=models.Index(fields=['tenant', 'created_at'], name='course_podc_tenant__6eb2c8_idx'),
        ),
        migrations.AddIndex(
            model_name='studynotes',
            index=models.Index(fields=['tenant', 'teacher', 'course'], name='study_notes_tenant__2f10c9_idx'),
        ),
        migrations.AddIndex(
            model_name='studynotes',
            index=models.Index(fields=['tenant', 'course', 'module'], name='study_notes_tenant__046769_idx'),
        ),
        migrations.AddIndex(
            model_name='studynotes',
            index=models.Index(fields=['tenant', 'teacher', '-created_at'], name='study_notes_tenant__36fcb0_idx'),
        ),
    ]
