# Generated by Django 5.2.11 on 2026-04-12 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial_academic_structure'),
        ('courses', '0019_course_assigned_students_and_more'),
        ('tenants', '0013_initial_academic_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('PD', 'Professional Development'), ('ACADEMIC', 'Academic')], default='PD', help_text='PD = admin creates for teachers, ACADEMIC = teacher creates for students', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Linked subject (required for ACADEMIC courses)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='target_grades',
            field=models.ManyToManyField(blank=True, help_text='Which grades this academic course targets', related_name='targeted_courses', to='academics.grade'),
        ),
        migrations.AddField(
            model_name='course',
            name='target_sections',
            field=models.ManyToManyField(blank=True, help_text='Specific sections targeted (if empty, targets all sections in target_grades)', related_name='targeted_courses', to='academics.section'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['tenant', 'course_type'], name='courses_tenant__4c4f2d_idx'),
        ),
    ]
