"""TenantAIConfig — Phase 9 media generation fields.

MAIC-901. Additive, reversible. Adds 9 new fields:

    Image:
      - image_model
      - image_base_url
      - image_default_size
      - image_default_quality
      (image_provider + image_api_key_encrypted already existed)

    Video:
      - video_provider (choice)
      - video_api_key_encrypted
      - video_model
      - video_base_url
      - video_default_duration

Plus extends ``image_provider`` choices with the upstream-compatible
roster (qwen, grok, minimax, nano_banana, seedream).

Hand-written, NOT autogenerated. The autodetector wanted to bundle
several unrelated index renames + field alters from repo migration
drift; isolating to one operation keeps this rollback-safe (same
pattern as MAIC-800 in apps/tenants/0032).
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0046_tenantaiconfig_minimax_tts"),
    ]

    operations = [
        # ── Image: extend provider choices ────────────────────────────
        migrations.AlterField(
            model_name="tenantaiconfig",
            name="image_provider",
            field=models.CharField(
                choices=[
                    ("openai", "DALL-E / gpt-image-1"),
                    ("stability", "Stability AI"),
                    ("qwen", "Qwen (Alibaba)"),
                    ("grok", "Grok (xAI)"),
                    ("minimax", "Minimax"),
                    ("nano_banana", "Nano-Banana"),
                    ("seedream", "Seedream"),
                    ("pollinations", "Pollinations (legacy v1 default)"),
                    ("disabled", "Disabled"),
                ],
                default="pollinations",
                max_length=20,
            ),
        ),
        # ── Image: new fields ─────────────────────────────────────────
        migrations.AddField(
            model_name="tenantaiconfig",
            name="image_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Model identifier for the chosen provider, e.g. "
                    "dall-e-3, gpt-image-1, qwen-image-plus, "
                    "stable-diffusion-3.5. Empty means use the "
                    "adapter's default."
                ),
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="tenantaiconfig",
            name="image_base_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text=(
                    "Custom base URL for the image provider — proxies, "
                    "regional endpoints, self-hosted Stability, etc. "
                    "Validated through apps/integrations_chat/ssrf_guard.py "
                    "at request time."
                ),
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="tenantaiconfig",
            name="image_default_size",
            field=models.CharField(
                default="1024x1024",
                help_text="Default WxH used when a request omits explicit dimensions.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="tenantaiconfig",
            name="image_default_quality",
            field=models.CharField(
                default="standard",
                help_text="Default quality tier passed to the adapter (standard|high).",
                max_length=20,
            ),
        ),
        # ── Video: 5 new fields ───────────────────────────────────────
        migrations.AddField(
            model_name="tenantaiconfig",
            name="video_provider",
            field=models.CharField(
                choices=[
                    ("veo", "Google Veo"),
                    ("kling", "Kling"),
                    ("minimax_video", "Minimax Video"),
                    ("seedance", "Seedance"),
                    ("grok_video", "Grok Video"),
                    ("disabled", "Disabled"),
                ],
                default="disabled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenantaiconfig",
            name="video_api_key_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tenantaiconfig",
            name="video_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Model identifier, e.g. veo-3, kling-v1.6, T2V-01.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="tenantaiconfig",
            name="video_base_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Custom base URL for the video provider; SSRF-guarded.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="tenantaiconfig",
            name="video_default_duration",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Default clip duration in seconds (provider-clamped at dispatch).",
            ),
        ),
    ]
