"""TenantAIConfig — Phase 10 PDF ingest fields.

MAIC-1001. Additive, reversible. Adds 3 new fields:
    pdf_provider (choice, default 'disabled')
    mineru_api_key_encrypted (Fernet-encrypted)
    mineru_base_url (optional custom Mineru endpoint)

Hand-written, NOT autogenerated. The autodetector wanted to bundle
unrelated repo migration drift (same situation as 0047 for Phase 9
media); isolating this migration keeps it rollback-safe.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0047_tenantaiconfig_media_phase9"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantaiconfig",
            name="pdf_provider",
            field=models.CharField(
                choices=[
                    ("mineru", "Mineru Cloud"),
                    ("disabled", "Disabled"),
                ],
                default="disabled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenantaiconfig",
            name="mineru_api_key_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tenantaiconfig",
            name="mineru_base_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text=(
                    "Custom Mineru endpoint — self-hosted instance or "
                    "regional endpoint. Empty means use the public "
                    "Mineru Cloud URL. SSRF-guarded at request time."
                ),
                max_length=500,
            ),
        ),
    ]
