# Generated by Django 5.2.13 on 2026-05-13 06:49

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_strip_placeholder_maic_image_urls'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aichatbotknowledge',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='aichatbotknowledge',
            name='ai_knowledge_chatbot_auto_idx',
        ),
        migrations.RemoveIndex(
            model_name='aichatbotknowledge',
            name='ai_knowledge_content_src_idx',
        ),
        migrations.RemoveIndex(
            model_name='parentsession',
            name='parent_sess_token_idx',
        ),
        migrations.RenameIndex(
            model_name='aichatbot',
            new_name='ai_chatbots_tenant__4e2e82_idx',
            old_name='ai_chatbots_tenant__idx1',
        ),
        migrations.RenameIndex(
            model_name='aichatbot',
            new_name='ai_chatbots_tenant__f86318_idx',
            old_name='ai_chatbots_tenant__idx2',
        ),
        migrations.RenameIndex(
            model_name='aichatbotchunk',
            new_name='ai_chatbot__tenant__e3eaf6_idx',
            old_name='ai_chatbot__tenant_chatbot_idx',
        ),
        migrations.RenameIndex(
            model_name='aichatbotconversation',
            new_name='ai_chatbot__tenant__f20b4d_idx',
            old_name='ai_chatbot__conv_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='aichatbotconversation',
            new_name='ai_chatbot__chatbot_76ffa7_idx',
            old_name='ai_chatbot__conv_chatbot_idx',
        ),
        migrations.RenameIndex(
            model_name='aichatbotconversation',
            new_name='ai_chatbot__tenant__fcbe8e_idx',
            old_name='ai_chatbot__conv_flagged_idx',
        ),
        migrations.RenameIndex(
            model_name='aichatbotknowledge',
            new_name='ai_chatbot__chatbot_55880c_idx',
            old_name='ai_chatbot__chatbot_idx',
        ),
        migrations.RenameIndex(
            model_name='aichatbotknowledge',
            new_name='ai_chatbot__tenant__93b028_idx',
            old_name='ai_knowledge_tenant_chatbot_idx',
        ),
        migrations.RenameIndex(
            model_name='coursetemplate',
            new_name='course_temp_categor_0e65bf_idx',
            old_name='course_tpl_cat_pub_idx',
        ),
        migrations.RenameIndex(
            model_name='coursetemplate',
            new_name='course_temp_languag_6d92ab_idx',
            old_name='course_tpl_lang_pub_idx',
        ),
        migrations.RenameIndex(
            model_name='coursetemplate',
            new_name='course_temp_level_a9edb3_idx',
            old_name='course_tpl_level_pub_idx',
        ),
        migrations.RenameIndex(
            model_name='maicclassroom',
            new_name='maic_classr_tenant__622c76_idx',
            old_name='maic_cls_tenant_creator_idx',
        ),
        migrations.RenameIndex(
            model_name='maicclassroom',
            new_name='maic_classr_tenant__2a07b8_idx',
            old_name='maic_cls_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='maicclassroom',
            new_name='maic_classr_tenant__5c0c6d_idx',
            old_name='maic_cls_tenant_public_idx',
        ),
        migrations.RenameIndex(
            model_name='maicclassroom',
            new_name='maic_classr_tenant__257873_idx',
            old_name='maic_cls_tenant_course_idx',
        ),
        migrations.RenameIndex(
            model_name='scormpackage',
            new_name='scorm_packa_tenant__07c303_idx',
            old_name='scorm_pkg_tenant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='scormtrackingdata',
            new_name='scorm_track_tenant__89ea90_idx',
            old_name='scorm_track_tenant_user_idx',
        ),
        migrations.RenameIndex(
            model_name='scormtrackingdata',
            new_name='scorm_track_package_25f29c_idx',
            old_name='scorm_track_pkg_user_idx',
        ),
        migrations.RenameIndex(
            model_name='studysummary',
            new_name='study_summa_tenant__da2b15_idx',
            old_name='study_summ_tenant_student_idx',
        ),
        migrations.RenameIndex(
            model_name='studysummary',
            new_name='study_summa_student_157d11_idx',
            old_name='study_summ_student_content_idx',
        ),
        migrations.RenameIndex(
            model_name='xapistatement',
            new_name='xapi_statem_tenant__809312_idx',
            old_name='xapi_stmt_tenant_stored_idx',
        ),
        migrations.RenameIndex(
            model_name='xapistatement',
            new_name='xapi_statem_tenant__fc16e8_idx',
            old_name='xapi_stmt_tenant_actor_idx',
        ),
        migrations.RenameIndex(
            model_name='xapistatement',
            new_name='xapi_statem_tenant__0384e3_idx',
            old_name='xapi_stmt_tenant_verb_idx',
        ),
        migrations.AlterField(
            model_name='content',
            name='ai_chatbot',
            field=models.ForeignKey(blank=True, help_text='Linked AI chatbot when content_type=CHATBOT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='courses.aichatbot'),
        ),
        migrations.AlterField(
            model_name='content',
            name='maic_classroom',
            field=models.ForeignKey(blank=True, help_text='Linked MAIC classroom when content_type=AI_CLASSROOM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='courses.maicclassroom'),
        ),
        migrations.AlterField(
            model_name='maicclassroom',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Legacy monolithic content field (PERF-P0-4). Read-only post-cutover — composed_content / content_scenes / content_agents / content_meta are the source of truth.'),
        ),
        migrations.AlterField(
            model_name='maicclassroom',
            name='images_pending',
            field=models.BooleanField(default=False, help_text='True while the fill_classroom_images Celery task is in-flight. Frontend polls this to know whether slide images are still loading.'),
        ),
        migrations.AlterField(
            model_name='parentmagictoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='parentsession',
            name='refresh_token',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='parentsession',
            name='session_token',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='scormpackage',
            name='launch_url',
            field=models.CharField(help_text='Relative launch URL inside the package', max_length=500),
        ),
        migrations.AlterField(
            model_name='scormpackage',
            name='manifest_path',
            field=models.CharField(help_text='Relative path to imsmanifest.xml', max_length=500),
        ),
        migrations.AlterField(
            model_name='scormpackage',
            name='package_path',
            field=models.CharField(help_text='Relative package root under MEDIA_ROOT', max_length=500),
        ),
        migrations.AlterField(
            model_name='scormpackage',
            name='package_size',
            field=models.BigIntegerField(default=0, help_text='Extracted size in bytes'),
        ),
        migrations.AlterField(
            model_name='xapistatement',
            name='statement_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='xAPI statement id (supplied by sender or generated)'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['module', 'is_active'], name='contents_module__3e7207_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content_type'], name='contents_content_4e46bd_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'is_active'], name='modules_course__aaf347_idx'),
        ),
    ]
