# Generated by Django 5.0.1 on 2026-02-16 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discussions", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="discussionreply",
            new_name="discussion__thread__8faa27_idx",
            old_name="dr_thread_created_idx",
        ),
        migrations.RenameIndex(
            model_name="discussionreply",
            new_name="discussion__author__4e3c05_idx",
            old_name="dr_author_created_idx",
        ),
        migrations.RenameIndex(
            model_name="discussionreply",
            new_name="discussion__parent__bbcf57_idx",
            old_name="dr_parent_idx",
        ),
        migrations.RenameIndex(
            model_name="discussionthread",
            new_name="discussion__tenant__30dece_idx",
            old_name="dt_tenant_course_status_idx",
        ),
        migrations.RenameIndex(
            model_name="discussionthread",
            new_name="discussion__tenant__561934_idx",
            old_name="dt_tenant_content_status_idx",
        ),
        migrations.RenameIndex(
            model_name="discussionthread",
            new_name="discussion__author__425646_idx",
            old_name="dt_author_created_idx",
        ),
    ]
