# Generated by Django 5.2.13 on 2026-05-02 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    # Dependencies edited to point at the actual latest migrations in the
    # repo (makemigrations auto-detected pre-existing model drift in courses
    # and tenants and tried to add phantom 0046_/0032_ as deps; we delete
    # those side-effect migration files since they're outside this ticket's
    # scope per the V1 freeze rule).
    dependencies = [
        ("courses", "0045_add_quiz_content_type"),
        ("tenants", "0031_auditlog_course_gen_flagged"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaicSessionV2",
            fields=[
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_event_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.course",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maic_v2_sessions_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "MAIC v2 session",
                "verbose_name_plural": "MAIC v2 sessions",
                "db_table": "maic_session_v2",
                "indexes": [
                    models.Index(
                        fields=["tenant", "created_at"], name="maic_sessio_tenant__519e42_idx"
                    )
                ],
            },
        ),
    ]
