# Generated by Django 5.2.13 on 2026-05-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maic', '0002_maic_generation_job'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='maicgenerationjob',
            new_name='maic_genera_tenant__427901_idx',
            old_name='maic_genjob_tenant_2c9d11_idx',
        ),
        migrations.RenameIndex(
            model_name='maicgenerationjob',
            new_name='maic_genera_status_4981b5_idx',
            old_name='maic_genjob_status_idx',
        ),
    ]
