# Generated by Django 5.0.1 on 2026-02-16 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0005_audit_log_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("VIDEO", "Video"), ("DOCUMENT", "Document"), ("LINK", "Link")],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="media_assets/%Y/%m/")),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "file_url",
                    models.URLField(blank=True, help_text="External URL or CDN path for file"),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                ("thumbnail_url", models.URLField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "media_assets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "media_type"], name="media_asset_tenant__649482_idx"
                    ),
                    models.Index(
                        fields=["tenant", "is_active"], name="media_asset_tenant__c8a02e_idx"
                    ),
                ],
            },
        ),
    ]
