# Generated by Django 5.2.11 on 2026-02-27 00:18

import utils.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=utils.storage_paths.media_asset_upload_to),
        ),
    ]
