# Generated by Django 5.0.1 on 2026-02-02 03:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="School name", max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=200, unique=True
                    ),
                ),
                (
                    "subdomain",
                    models.CharField(
                        help_text="e.g., schoolname.lms.com",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary contact email", max_length=254
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#1F4788", help_text="Hex color code", max_length=7
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_trial", models.BooleanField(default=True)),
                ("trial_end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tenants",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="tenants_slug_3181c2_idx"),
                    models.Index(
                        fields=["subdomain"], name="tenants_subdoma_69cf01_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="tenants_is_acti_ec1713_idx"
                    ),
                ],
            },
        ),
    ]
