# Generated by Django 5.0.1 on 2026-02-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="font_family",
            field=models.CharField(
                blank=True,
                default="Inter",
                help_text="CSS font-family name",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="secondary_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional hex color code",
                max_length=7,
            ),
        ),
    ]
