# Generated by Django 5.0.1 on 2026-02-15 10:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0004_tenant_sso_2fa_custom_domain"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("PUBLISH", "Publish"),
                            ("UNPUBLISH", "Unpublish"),
                            ("DEACTIVATE", "Deactivate"),
                            ("ACTIVATE", "Activate"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("SETTINGS_CHANGE", "Settings Change"),
                            ("IMPORT", "Bulk Import"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(help_text="e.g. 'User', 'Course'", max_length=100),
                ),
                ("target_id", models.CharField(blank=True, max_length=255)),
                ("target_repr", models.CharField(blank=True, max_length=500)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("request_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RenameIndex(
            model_name="tenant",
            new_name="tenants_custom__b86538_idx",
            old_name="tenants_custom_domain_idx",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant", "timestamp"], name="audit_logs_tenant__eb751d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["actor", "timestamp"], name="audit_logs_actor_i_ce2144_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["target_type", "target_id"], name="audit_logs_target__9fc8de_idx"
            ),
        ),
    ]
