# Generated by Django 5.2.11 on 2026-02-21 09:06

import utils.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_audit_log_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='maintenance_mode_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='maintenance_mode_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='maintenance_mode_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.storage_paths.tenant_logo_upload_to),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['maintenance_mode_enabled'], name='tenants_mainten_099992_idx'),
        ),
    ]
