# Generated by Django 5.2.11 on 2026-02-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_maintenance_mode_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='feature_teacher_authoring',
            field=models.BooleanField(default=False),
        ),
    ]
