# Generated by Django 5.2.11 on 2026-02-26 02:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_feature_teacher_authoring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('source', models.CharField(choices=[('cal_webhook', 'Cal.com Webhook'), ('manual', 'Manual Entry')], default='manual', max_length=20)),
                ('cal_event_id', models.CharField(blank=True, default='', max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('followup_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_demo_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'demo_bookings',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['status'], name='demo_bookin_status_76b3ca_idx'), models.Index(fields=['email'], name='demo_bookin_email_2092fb_idx'), models.Index(fields=['scheduled_at'], name='demo_bookin_schedul_2fe638_idx')],
            },
        ),
    ]
