# Generated by Django 5.2.11 on 2026-02-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_demobooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="email_bucket_prefix",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional bucket prefix for outbound email analytics",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="notification_from_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional display sender name for school notifications",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="notification_reply_to",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Reply-to email for school notifications",
                max_length=254,
            ),
        ),
    ]
