# Generated by Django 5.2.11 on 2026-03-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenant_notification_sender_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
