# Generated by Django 5.2.11 on 2026-04-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='feature_ai_studio',
            field=models.BooleanField(default=False, help_text='AI lesson builder & interactive slides'),
        ),
    ]
