# Generated by Django 5.2.11 on 2026-04-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_add_feature_ai_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='feature_students',
            field=models.BooleanField(default=False, help_text='Enable student portal'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_students',
            field=models.PositiveIntegerField(default=50, help_text='Max student accounts'),
        ),
    ]
