# Generated by Django 5.2.11 on 2026-04-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenant_feature_students_tenant_max_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='academic_year_end_date',
            field=models.DateField(blank=True, help_text='End date of the current academic year', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='academic_year_start_date',
            field=models.DateField(blank=True, help_text='Start date of the current academic year', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='current_academic_year',
            field=models.CharField(blank=True, default='', help_text='Current academic year, e.g. 2026-27', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_prefix',
            field=models.CharField(blank=True, default='', help_text='Prefix for auto-generated user IDs, e.g. KIS', max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='login_bg_image',
            field=models.URLField(blank=True, default='', help_text='Background image URL for the login page', max_length=500),
        ),
        migrations.AddField(
            model_name='tenant',
            name='school_motto',
            field=models.CharField(blank=True, default='', help_text="Footer/about text, e.g. 'Powered by the Idea-Loom Model'", max_length=200),
        ),
        migrations.AddField(
            model_name='tenant',
            name='student_id_counter',
            field=models.PositiveIntegerField(default=1, help_text='Next sequence number for student ID generation (atomic)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='teacher_id_counter',
            field=models.PositiveIntegerField(default=1, help_text='Next sequence number for teacher ID generation (atomic)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='welcome_message',
            field=models.CharField(blank=True, default='', help_text="Dashboard greeting message, e.g. 'Welcome to Keystone Learning'", max_length=200),
        ),
        migrations.AddField(
            model_name='tenant',
            name='white_label',
            field=models.BooleanField(default=False, help_text='When enabled, hides all LearnPuddle branding'),
        ),
    ]
