# Generated by Django 5.2.13 on 2026-05-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0032_tenant_feature_maic_v2'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='complianceitem',
            new_name='compliance__tenant__4dc237_idx',
            old_name='compliance__tenant__cat_idx',
        ),
        migrations.RenameIndex(
            model_name='rankingentry',
            new_name='ranking_ent_tenant__d484e9_idx',
            old_name='ranking_ent_tenant__idx',
        ),
        migrations.RenameIndex(
            model_name='rankingentry',
            new_name='ranking_ent_platfor_f3f11b_idx',
            old_name='ranking_ent_platfor_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolaccreditation',
            new_name='school_accr_tenant__7a013a_idx',
            old_name='school_accr_tenant__idx',
        ),
        migrations.RenameIndex(
            model_name='schoolaccreditation',
            new_name='school_accr_status_a21a89_idx',
            old_name='school_accr_status_idx',
        ),
        migrations.RenameIndex(
            model_name='staffcertification',
            new_name='staff_certi_tenant__bc39bb_idx',
            old_name='staff_cert_tenant_type_idx',
        ),
        migrations.RenameIndex(
            model_name='staffcertification',
            new_name='staff_certi_tenant__9349eb_idx',
            old_name='staff_cert_tenant_teacher_idx',
        ),
        migrations.RenameIndex(
            model_name='staffcertification',
            new_name='staff_certi_status_2125e6_idx',
            old_name='staff_cert_status_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PUBLISH', 'Publish'), ('UNPUBLISH', 'Unpublish'), ('DEACTIVATE', 'Deactivate'), ('ACTIVATE', 'Activate'), ('PASSWORD_RESET', 'Password Reset'), ('SETTINGS_CHANGE', 'Settings Change'), ('IMPORT', 'Bulk Import'), ('RUN_REPORT', 'Run Report'), ('EXPORT_REPORT', 'Export Report'), ('EXPORT_SCORM', 'Export SCORM'), ('IMPORT_SCORM', 'Import SCORM'), ('CHAT_INTEGRATION_CREATED', 'Chat Integration Created'), ('CHAT_INTEGRATION_DELETED', 'Chat Integration Deleted'), ('CHAT_DELIVERY_FAILED', 'Chat Delivery Failed (DLQ)'), ('CONNECT_CALENDAR', 'Calendar Connected'), ('DISCONNECT_CALENDAR', 'Calendar Disconnected'), ('SYNC_CALENDAR_ERROR', 'Calendar Sync Error'), ('TRANSLATION_STARTED', 'Translation Started'), ('TRANSLATION_FINISHED', 'Translation Finished'), ('TRANSLATION_FAILED', 'Translation Failed'), ('TRANSLATION_PURGED', 'Translation Purged'), ('SEMANTIC_REINDEX_STARTED', 'Semantic Reindex Started'), ('SEMANTIC_REINDEX_FINISHED', 'Semantic Reindex Finished'), ('SEMANTIC_REINDEX_FAILED', 'Semantic Reindex Failed'), ('COURSE_GENERATION_STARTED', 'Course Generation Started'), ('COURSE_GENERATION_SUCCEEDED', 'Course Generation Succeeded'), ('COURSE_GENERATION_FAILED', 'Course Generation Failed'), ('COURSE_MATERIALISED', 'Course Materialised'), ('COURSE_GENERATION_PURGED', 'Course Generation Purged'), ('CHAT_QUERY_ASKED', 'Chat Query Asked'), ('CHAT_QUERY_PURGED', 'Chat Query Purged'), ('TRANSLATION_FIELD_APPROVED', 'Translation Field Approved'), ('TRANSLATION_FIELD_REJECTED', 'Translation Field Rejected'), ('TRANSLATION_FIELD_EDITED', 'Translation Field Edited'), ('TRANSLATION_PUBLISHED', 'Translation Published')], max_length=30),
        ),
        migrations.AlterField(
            model_name='schoolaccreditation',
            name='status',
            field=models.CharField(choices=[('AUTHORIZED', 'Authorized / Active'), ('CANDIDACY', 'Candidacy / In Progress'), ('CONSIDERATION', 'Under Consideration'), ('PENDING', 'Application Pending'), ('EXPIRED', 'Expired'), ('NOT_STARTED', 'Not Started')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='feature_maic',
            field=models.BooleanField(default=False, help_text='Enable OpenMAIC AI Classroom feature (v1, legacy)'),
        ),
        migrations.AlterField(
            model_name='tenantsamlconfig',
            name='sp_private_key',
            field=models.TextField(blank=True, default='', help_text='PEM-encoded SP private key — persisted Fernet-encrypted at rest.'),
        ),
    ]
