# Generated by Django 5.2.13 on 2026-05-13 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_rename_chatquery_user_index'),
        ('courses', '0051_alter_aichatbotknowledge_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatquery',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Optional course scope for the query.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_queries', to='courses.course'),
        ),
    ]
