# Generated by Django 5.2.14 on 2026-07-13 03:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0051_alter_aichatbotknowledge_managers_and_more'),
        ('tenants', '0033_rename_compliance__tenant__cat_idx_compliance__tenant__4dc237_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenMAICJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upstream_job_id', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openmaic_jobs', to='courses.maicclassroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openmaic_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'openmaic_jobs',
            },
        ),
        migrations.CreateModel(
            name='AIUsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('modality', models.CharField(choices=[('llm', 'Large language model'), ('tts', 'Text to speech'), ('asr', 'Speech recognition'), ('image', 'Image generation'), ('video', 'Video generation'), ('pdf', 'Document parsing'), ('web_search', 'Web search')], max_length=20)),
                ('provider_id', models.CharField(max_length=80)),
                ('model_id', models.CharField(blank=True, default='', max_length=160)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveBigIntegerField(default=0)),
                ('cache_creation_tokens', models.PositiveBigIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveBigIntegerField(default=0)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('unit', models.CharField(default='token', max_length=24)),
                ('source', models.CharField(blank=True, default='', max_length=80)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_events', to='courses.maicclassroom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_events', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='ai_classroom.openmaicjob')),
            ],
            options={
                'db_table': 'ai_usage_events',
            },
        ),
        migrations.CreateModel(
            name='AIQuotaReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('consumed', 'Consumed'), ('released', 'Released'), ('expired', 'Expired')], default='reserved', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_quota_reservations', to='courses.maicclassroom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_quota_reservations', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota_reservation', to='ai_classroom.openmaicjob')),
            ],
            options={
                'db_table': 'ai_quota_reservations',
            },
        ),
        migrations.CreateModel(
            name='TenantAIProviderCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modality', models.CharField(choices=[('llm', 'Large language model'), ('tts', 'Text to speech'), ('asr', 'Speech recognition'), ('image', 'Image generation'), ('video', 'Video generation'), ('pdf', 'Document parsing'), ('web_search', 'Web search')], max_length=20)),
                ('provider_id', models.SlugField(max_length=80)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('base_url', models.URLField(blank=True, default='', max_length=500)),
                ('model_allowlist', models.JSONField(blank=True, default=list)),
                ('provider_config', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('failed', 'Failed')], default='unverified', max_length=16)),
                ('verification_message', models.CharField(blank=True, default='', max_length=500)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_credentials', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_ai_provider_credentials',
                'ordering': ['modality', 'provider_id'],
            },
        ),
        migrations.CreateModel(
            name='TenantAIRuntimeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('runtime', models.CharField(choices=[('legacy', 'Legacy LearnPuddle runtime'), ('openmaic_fork', 'OpenMAIC fork')], db_index=True, default='legacy', max_length=24)),
                ('student_generation_enabled', models.BooleanField(default=False)),
                ('provider_config_version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runtime_config', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_ai_runtime_configs',
            },
        ),
        migrations.CreateModel(
            name='AIClassroomArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=700)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('schema_version', models.CharField(default='openmaic-1', max_length=40)),
                ('runtime_version', models.CharField(max_length=80)),
                ('upstream_classroom_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='openmaic_artifact', to='courses.maicclassroom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'ai_classroom_artifacts',
                'indexes': [models.Index(fields=['tenant', 'classroom'], name='ai_classroo_tenant__79c546_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='openmaicjob',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='openmaic_jo_tenant__edb170_idx'),
        ),
        migrations.AddConstraint(
            model_name='openmaicjob',
            constraint=models.UniqueConstraint(fields=('tenant', 'upstream_job_id'), name='uniq_tenant_openmaic_job'),
        ),
        migrations.AddConstraint(
            model_name='openmaicjob',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uniq_tenant_openmaic_idempotency'),
        ),
        migrations.AddIndex(
            model_name='aiusageevent',
            index=models.Index(fields=['tenant', 'occurred_at'], name='ai_usage_ev_tenant__f2e6ea_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusageevent',
            index=models.Index(fields=['tenant', 'modality', 'occurred_at'], name='ai_usage_ev_tenant__abbffa_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiusageevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uniq_tenant_ai_usage_event'),
        ),
        migrations.AddIndex(
            model_name='aiquotareservation',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='ai_quota_re_tenant__e4ffcc_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantaiprovidercredential',
            index=models.Index(fields=['tenant', 'modality', 'is_enabled'], name='tenant_ai_p_tenant__812704_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantaiprovidercredential',
            constraint=models.UniqueConstraint(fields=('tenant', 'modality', 'provider_id'), name='uniq_tenant_ai_provider'),
        ),
        migrations.AddConstraint(
            model_name='tenantaiprovidercredential',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant', 'modality'), name='uniq_tenant_ai_default_provider'),
        ),
    ]
