# Generated by Django 5.2.14 on 2026-07-13 03:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_classroom", "0002_migrate_legacy_tenant_ai_config"),
        ("courses", "0051_alter_aichatbotknowledge_managers_and_more"),
        (
            "tenants",
            "0033_rename_compliance__tenant__cat_idx_compliance__tenant__4dc237_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIClassroomMediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("poster", "Poster"),
                            ("attachment", "Attachment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("sha256", models.CharField(max_length=64)),
                ("extension", models.CharField(max_length=12)),
                ("content_type", models.CharField(max_length=120)),
                ("object_key", models.CharField(max_length=700)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openmaic_media_assets",
                        to="courses.maicclassroom",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="openmaic_media_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "ai_classroom_media_assets",
                "indexes": [
                    models.Index(
                        fields=["tenant", "classroom", "kind"],
                        name="ai_classroo_tenant__ce9a95_idx",
                    ),
                    models.Index(
                        fields=["tenant", "is_confirmed", "created_at"],
                        name="ai_classroo_tenant__122b8b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "classroom", "kind", "sha256"),
                        name="uniq_ai_classroom_media_content",
                    )
                ],
            },
        ),
    ]
